Repository nasa/osal, pull requests merged in 2020-06, with the labels that each got.

#467 Fix #449, Rename BSPs to be generic
  .travis.yml
  src/bsp/generic-linux/CMakeLists.txt
  src/bsp/generic-linux/build_options.cmake
  src/bsp/generic-linux/src/bsp_console.c
  src/bsp/generic-linux/src/bsp_start.c
  src/bsp/generic-linux/src/generic_linux_bsp_internal.h
  src/bsp/generic-vxworks/CMakeLists.txt
  src/bsp/generic-vxworks/build_options.cmake
  src/bsp/generic-vxworks/src/bsp_console.c
  src/bsp/generic-vxworks/src/bsp_start.c
  src/bsp/generic-vxworks/src/generic_vxworks_bsp_internal.h
  src/bsp/mcp750-vxworks/CMakeLists.txt
  src/bsp/mcp750-vxworks/src/bsp.mak
Labels: CCB-20200520, IC-20200527, code reviewed, enhancement

#480 Fix #479, add name association to stub arguments
  ut_assert/inc/utstubs.h
  ut_assert/src/utstubs.c
Labels: CCB-20200527, IC-20200527, code reviewed

#452 Fix #381, Add OS_TimerAdd functional test
  src/tests/timer-add-api-test/timer-add-api-test.c
Labels: CCB-20200513, IC-20200527, code reviewed, enhancement

#481 Fix #380, Add OS_TimeBase Api Functional Tests
  src/tests/time-base-api-test/time-base-api-test.c
Labels: CCB-20200527, IC-20200527

#495 Fix #493, race condition in idmap api test
  src/tests/idmap-api-test/idmap-api-test.c
Labels: CCB-Fast Track, CCB-READY, IC-20200527

#487 Integration Candidate: 2020-05-27
  .travis.yml
  README.md
  src/bsp/generic-linux/CMakeLists.txt
  src/bsp/generic-linux/build_options.cmake
  src/bsp/generic-linux/src/bsp_console.c
  src/bsp/generic-linux/src/bsp_start.c
  src/bsp/generic-linux/src/generic_linux_bsp_internal.h
  src/bsp/generic-vxworks/CMakeLists.txt
  src/bsp/generic-vxworks/build_options.cmake
  src/bsp/generic-vxworks/src/bsp_console.c
  src/bsp/generic-vxworks/src/bsp_start.c
  src/bsp/generic-vxworks/src/generic_vxworks_bsp_internal.h
  src/bsp/mcp750-vxworks/CMakeLists.txt
  src/bsp/mcp750-vxworks/src/bsp.mak
  src/os/inc/osapi-version.h
  src/tests/idmap-api-test/idmap-api-test.c
  src/tests/time-base-api-test/time-base-api-test.c
  src/tests/timer-add-api-test/timer-add-api-test.c
  ut_assert/inc/utstubs.h
  ut_assert/src/utstubs.c
Labels: IC-20200527

#486 Fix #485 - add text to make clear that IDs are non-zero
  src/os/inc/osapi-os-core.h
  src/os/inc/osapi-os-filesys.h
  src/os/inc/osapi-os-loader.h
  src/os/inc/osapi-os-net.h
  src/os/inc/osapi-os-timer.h
Labels: CCB-20200603, IC-20200610, code reviewed, docs, enhancement

#497 Fix #494, add missing stub functions for OSAL API
  src/ut-stubs/osapi-utstub-file.c
  src/ut-stubs/osapi-utstub-filesys.c
  src/ut-stubs/osapi-utstub-printf.c
  src/ut-stubs/osapi-utstub-task.c
Labels: CCB-20200610, IC-20200610, code reviewed

#492 Fix #491, increase UT assert buffer sizes
  ut_assert/src/utassert.c
Labels: CCB-20200610, IC-20200610, code reviewed

#511 Integration Candidate 2020-06-10
  README.md
  src/os/inc/osapi-os-core.h
  src/os/inc/osapi-os-filesys.h
  src/os/inc/osapi-os-loader.h
  src/os/inc/osapi-os-net.h
  src/os/inc/osapi-os-timer.h
  src/os/inc/osapi-version.h
  src/ut-stubs/osapi-utstub-file.c
  src/ut-stubs/osapi-utstub-filesys.c
  src/ut-stubs/osapi-utstub-printf.c
  src/ut-stubs/osapi-utstub-task.c
  ut_assert/src/utassert.c
Labels: IC-20200610

#503 Fix #502, Add extra assert macros
  ut_assert/inc/utassert.h
Labels: CCB-20200617, CCB-FastTrack, IC-20200610

#510 Fix #509, Remove uintmax_t usage
  ut_assert/src/utstubs.c
Labels: CCB-20200617, CCB-FastTrack, IC-20200610

#513 Fast Track for Integration Candidate 2020-06-10
  README.md
  ut_assert/inc/utassert.h
  ut_assert/src/utstubs.c
Labels: IC-20200610

#500 Fix #499, store all arguments in generic-linux BSP
  src/bsp/generic-linux/src/bsp_start.c
Labels: CCB-20200617, IC-20200617, code reviewed

#504 Fix #501, add PIC library for ut assert
  ut_assert/CMakeLists.txt
  ut_assert/inc/utassert.h
  ut_assert/inc/utbsp.h
  ut_assert/inc/uttest.h
  ut_assert/src/utassert.c
  ut_assert/src/utbsp.c
  ut_assert/src/utglobal.h
  ut_assert/src/uttest.c
Labels: CCB-20200617, IC-20200617, code reviewed

#518 Fix #516, Use absolute timeout for timedlock calls
  src/os/posix/src/os-impl-binsem.c
Labels: CCB-FastTrack, CCB-READY, IC-20200617, bug

#507 Fix #505, warnings in time base API test
  src/tests/time-base-api-test/time-base-api-test.c
Labels: CCB-20200617, IC-20200617, code reviewed

#508 Fix #506, enforce nonzero stack size
  src/os/posix/src/os-impl-tasks.c
  src/os/shared/src/osapi-task.c
  src/tests/idmap-api-test/idmap-api-test.c
  src/unit-test-coverage/shared/src/coveragetest-task.c
Labels: CCB-20200617, IC-20200617, code reviewed
