Repository nasa/osal, pull requests merged in 2020-11, with the labels that each got.

#633 Fix #327 and #333, Squash LGTM warnings
  src/os/inc/osapi-os-filesys.h
  src/os/portable/os-impl-bsd-sockets.c
  src/os/portable/os-impl-posix-files.c
  src/os/shared/src/osapi-filesys.c
  src/os/shared/src/osapi-select.c
  src/unit-test-coverage/portable/src/coveragetest-posix-files.c
  src/unit-test-coverage/ut-stubs/inc/OCS_stat.h
  src/unit-test-coverage/ut-stubs/override_inc/stat.h
  src/unit-test-coverage/ut-stubs/src/posix-stat-stubs.c
  src/unit-tests/oscore-test/ut_oscore_countsem_test.c
Labels: CCB-20201028, IC-20201103

#629 Fix #628, Update UtAssert macros with dynamic string formatting
  ut_assert/inc/utassert.h
Labels: CCB-20201028, IC-20201103, enhancement, unit-test

#639 Integration Candidate: 2020-11-03
  README.md
  src/os/inc/osapi-os-filesys.h
  src/os/inc/osapi-version.h
  src/os/portable/os-impl-bsd-sockets.c
  src/os/portable/os-impl-posix-files.c
  src/os/shared/inc/os-shared-mutex.h
  src/os/shared/src/osapi-filesys.c
  src/os/shared/src/osapi-mutex.c
  src/os/shared/src/osapi-select.c
  src/unit-test-coverage/portable/src/coveragetest-posix-files.c
  src/unit-test-coverage/ut-stubs/inc/OCS_stat.h
  src/unit-test-coverage/ut-stubs/override_inc/stat.h
  src/unit-test-coverage/ut-stubs/src/posix-stat-stubs.c
  src/unit-tests/oscore-test/ut_oscore_countsem_test.c
  ut_assert/inc/utassert.h
Labels: IC-20201103

#638 Fix #637, fix OS_ModuleUnload for static modules
  src/os/shared/inc/os-shared-module.h
  src/os/shared/src/osapi-module.c
Labels: CCB-20201104, IC-20201110

#643 Fix #641, add OS_ModuleLoad flags
  src/os/inc/osapi-os-loader.h
  src/os/portable/os-impl-no-symtab.c
  src/os/portable/os-impl-posix-dl-loader.c
  src/os/portable/os-impl-posix-dl-symtab.c
  src/os/shared/inc/os-shared-module.h
  src/os/shared/src/osapi-module.c
  src/os/vxworks/src/os-impl-symtab.c
  src/unit-test-coverage/shared/adaptors/inc/ut-adaptor-module.h
  src/unit-test-coverage/shared/adaptors/src/ut-adaptor-module.c
  src/unit-test-coverage/shared/src/coveragetest-module.c
  src/unit-test-coverage/ut-stubs/src/osapi-loader-impl-stubs.c
  src/unit-test-coverage/vxworks/src/coveragetest-symtab.c
  src/unit-tests/osloader-test/ut_osloader_module_test.c
  src/unit-tests/osloader-test/ut_osloader_symtable_test.c
  src/unit-tests/osloader-test/ut_osloader_symtable_test.h
  src/unit-tests/osloader-test/ut_osloader_test.c
  src/ut-stubs/osapi-utstub-module.c
Labels: CCB-20201104, IC-20201110

#652 Integration Candidate: 2020-11-10
  README.md
  src/os/inc/osapi-os-loader.h
  src/os/inc/osapi-version.h
  src/os/portable/os-impl-no-symtab.c
  src/os/portable/os-impl-posix-dl-loader.c
  src/os/portable/os-impl-posix-dl-symtab.c
  src/os/shared/inc/os-shared-module.h
  src/os/shared/src/osapi-module.c
  src/os/vxworks/src/os-impl-symtab.c
  src/unit-test-coverage/shared/adaptors/inc/ut-adaptor-module.h
  src/unit-test-coverage/shared/adaptors/src/ut-adaptor-module.c
  src/unit-test-coverage/shared/src/coveragetest-module.c
  src/unit-test-coverage/ut-stubs/src/osapi-loader-impl-stubs.c
  src/unit-test-coverage/vxworks/src/coveragetest-symtab.c
  src/unit-tests/osloader-test/ut_osloader_module_test.c
  src/unit-tests/osloader-test/ut_osloader_symtable_test.c
  src/unit-tests/osloader-test/ut_osloader_symtable_test.h
  src/unit-tests/osloader-test/ut_osloader_test.c
  src/ut-stubs/osapi-utstub-module.c
Labels: IC-20201110
