Repository nasa/osal, pull requests merged in 2020-04, with the labels that each got.

#372 Fix #349, OS_SocketAccept() fix
  src/os/shared/osapi-sockets.c
Labels: CCB - 20200325, IC - 20200325, code reviewed

#401 Integration Candidate 2020-03-25
  README.md
  src/os/inc/osapi-version.h
  src/os/shared/osapi-sockets.c
Labels: IC - 20200325

#386 Fix #18 Deprecate shared memory APIs
  src/os/inc/osapi-os-core.h
  src/unit-test-coverage/ut-stubs/src/osapi-base-impl-stubs.c
Labels: CCB - 20200401, IC - 20200401, code reviewed, enhancement

#388 Fix #347, replaces task_1_work with correct variable names
  src/tests/bin-sem-flush-test/bin-sem-flush-test.c
Labels: CCB - 20200401, IC - 20200401, code reviewed

#394 Fix #389, Resolve CI config warnings
  .travis.yml
Labels: CCB - 20200401, IC - 20200401, code reviewed, enhancement

#387 Fixes #259, updated osapi-filesys.c + ut_osfilesys_diskio_tes.ct to use…
  src/os/shared/osapi-filesys.c
  src/unit-tests/osfilesys-test/ut_osfilesys_diskio_test.c
Labels: CCB - 20200401, IC - 20200401, code reviewed, enhancement

#396 Fix #385, Deprecate interrupt related APIs
  src/os/inc/osapi-os-core.h
  src/os/posix/osapi.c
  src/os/rtems/osapi.c
  src/os/shared/os-impl.h
  src/os/shared/osapi-interrupts.c
  src/os/vxworks/osapi.c
  src/unit-test-coverage/posix/src/coveragetest-osapi.c
  src/unit-test-coverage/shared/src/coveragetest-interrupts.c
  src/unit-test-coverage/ut-stubs/src/osapi-base-impl-stubs.c
  src/unit-test-coverage/vxworks/src/coveragetest-osapi.c
  src/unit-tests/oscore-test/CMakeLists.txt
  src/unit-tests/oscore-test/ut_oscore_interrupt_test.c
  src/unit-tests/oscore-test/ut_oscore_test.c
Labels: CCB - 20200401, IC - 20200401, code reviewed, enhancement

#408 Integration Candidate 2020-04-01
  .travis.yml
  README.md
  src/os/inc/osapi-os-core.h
  src/os/inc/osapi-version.h
  src/os/posix/osapi.c
  src/os/rtems/osapi.c
  src/os/shared/os-impl.h
  src/os/shared/osapi-filesys.c
  src/os/shared/osapi-interrupts.c
  src/os/vxworks/osapi.c
  src/tests/bin-sem-flush-test/bin-sem-flush-test.c
  src/unit-test-coverage/posix/src/coveragetest-osapi.c
  src/unit-test-coverage/shared/src/coveragetest-interrupts.c
  src/unit-test-coverage/ut-stubs/src/osapi-base-impl-stubs.c
  src/unit-test-coverage/vxworks/src/coveragetest-osapi.c
  src/unit-tests/oscore-test/CMakeLists.txt
  src/unit-tests/oscore-test/ut_oscore_interrupt_test.c
  src/unit-tests/oscore-test/ut_oscore_test.c
  src/unit-tests/osfilesys-test/ut_osfilesys_diskio_test.c
Labels: IC - 20200401

#405 Fix #397, Remove old unit test example, add README.md, further macro cleanup
  src/unit-tests/README.md
  src/unit-tests/inc/ut_os_support.h
  src/unit-tests/oscore-test/ut_oscore_binsem_test.c
  src/unit-tests/oscore-test/ut_oscore_countsem_test.c
  src/unit-tests/oscore-test/ut_oscore_exception_test.c
  src/unit-tests/oscore-test/ut_oscore_misc_test.c
  src/unit-tests/oscore-test/ut_oscore_mutex_test.c
  src/unit-tests/oscore-test/ut_oscore_queue_test.c
  src/unit-tests/oscore-test/ut_oscore_task_test.c
  src/unit-tests/osfile-test/ut_osfile_dirio_test.c
  src/unit-tests/osfile-test/ut_osfile_fileio_test.c
  src/unit-tests/osfilesys-test/ut_osfilesys_diskio_test.c
  src/unit-tests/osloader-test/ut_osloader_module_test.c
  src/unit-tests/osloader-test/ut_osloader_symtable_test.c
  src/unit-tests/osnetwork-test/ut_osnetwork_misc_test.c
  src/unit-tests/ostimer-test/ut_ostimer_timerio_test.c
Labels: CCB - 20200408, IC - 20200408, code reviewed, enhancement, unit testing

#402 Fix #232, pthread stack min typo
  src/os/posix/osapi.c
Labels: CCB - 20200408, code reviewed, enhancement

#404 Fix #261, #312, and #362, OSAL build cleanup (multiple issues)
  CMakeLists.txt
  src/bsp/mcp750-vxworks/CMakeLists.txt
  src/bsp/mcp750-vxworks/build_options.cmake
  src/bsp/mcp750-vxworks/make/compiler-opts.mak
  src/bsp/mcp750-vxworks/make/link-rules.mak
  src/bsp/mcp750-vxworks/src/bsp_console.c
  src/bsp/mcp750-vxworks/src/bsp_start.c
  src/bsp/mcp750-vxworks/src/mcp750_bsp_internal.h
  src/bsp/mcp750-vxworks/ut-src/bsp_ut.c
  src/bsp/mcp750-vxworks/ut-src/bsp_ut_voltab.c
  src/bsp/pc-linux/CMakeLists.txt
  src/bsp/pc-linux/build_options.cmake
  src/bsp/pc-linux/make/build_options.cmake
  src/bsp/pc-linux/src/bsp_console.c
  src/bsp/pc-linux/src/bsp_start.c
  src/bsp/pc-linux/src/bsp_voltab.c
  src/bsp/pc-linux/src/pclinux_bsp_internal.h
  src/bsp/pc-linux/ut-src/bsp_ut.c
  src/bsp/pc-linux/ut-src/bsp_ut_voltab.c
  src/bsp/pc-rtems/CMakeLists.txt
  src/bsp/pc-rtems/build_options.cmake
  src/bsp/pc-rtems/make/build_options.cmake
  src/bsp/pc-rtems/src/bsp_console.c
  src/bsp/pc-rtems/src/bsp_start.c
  src/bsp/pc-rtems/src/pcrtems_bsp_internal.h
  src/bsp/pc-rtems/ut-src/bsp_ut.c
  src/bsp/pc-rtems/ut-src/bsp_ut_voltab.c
  src/bsp/shared/bsp-impl.h
  src/bsp/shared/bsp_default_app_run.c
  src/bsp/shared/bsp_default_app_startup.c
  src/bsp/shared/bsp_default_symtab.c
  src/bsp/shared/osapi-bsp.c
  src/os/inc/osapi-os-core.h
  src/os/posix/CMakeLists.txt
  src/os/posix/build_options.cmake
  src/os/posix/osapi.c
  src/os/rtems/CMakeLists.txt
  src/os/rtems/build_options.cmake
  src/os/vxworks/CMakeLists.txt
  src/os/vxworks/build_options.cmake
  src/unit-test-coverage/CMakeLists.txt
  src/unit-test-coverage/posix/modules/CMakeLists.txt
  src/unit-test-coverage/posix/ut-stubs/src/osapi-impl-posix-stubs.c
  src/unit-test-coverage/shared/modules/CMakeLists.txt
  src/unit-test-coverage/shared/src/coveragetest-filesys.c
  src/unit-test-coverage/ut-stubs/CMakeLists.txt
  src/unit-test-coverage/vxworks/CMakeLists.txt
  src/unit-test-coverage/vxworks/modules/CMakeLists.txt
  src/unit-tests/CMakeLists.txt
  src/ut-stubs/CMakeLists.txt
  ut_assert/CMakeLists.txt
  ut_assert/inc/utbsp.h
  ut_assert/src/utbsp.c
Labels: CCB - 20200408

#406 Fix #12, Comment update to correct for microseconds not always rounding up + a…
  src/os/posix/ostimer.c
  src/os/shared/osapi-common.c
  src/unit-test-coverage/shared/src/coveragetest-common.c
Labels: CCB - 20200415, IC - 20200415, code reviewed

#411 Fix #407, Resolve doxygen warnings for main doc
  src/os/inc/osapi-os-core.h
Labels: CCB - 20200415, IC - 20200415, code reviewed, docs

#398 Fix #88, Add test for name too long and update comments
  src/bsp/mcp750-vxworks/config/osconfig.h
  src/bsp/pc-linux/config/osconfig.h
  src/bsp/pc-rtems/config/osconfig.h
  src/os/inc/osapi-os-core.h
  src/os/inc/osapi-os-net.h
  src/os/inc/osapi-os-timer.h
  src/os/inc/osapi.h
  src/unit-tests/ostimer-test/ut_ostimer_timerio_test.c
Labels: CCB - 20200415, IC - 20200415, code reviewed

#414 Fix #368, Deprecate os_fs_err_name_t
  src/os/inc/osapi-os-filesys.h
  src/tests/file-api-test/file-api-test.c
Labels: CCB - 20200415, IC - 20200415, code reviewed, enhancement

#418 Fix #354, Shell related API separated for optional implementation
  src/os/portable/os-impl-no-shell.c
  src/os/posix/CMakeLists.txt
  src/os/posix/osfileapi.c
  src/os/posix/osshell.c
  src/os/rtems/CMakeLists.txt
  src/os/rtems/osfileapi.c
  src/os/rtems/osshell.c
  src/os/vxworks/CMakeLists.txt
  src/os/vxworks/osfileapi.c
  src/os/vxworks/osshell.c
  src/unit-test-coverage/vxworks/CMakeLists.txt
  src/unit-test-coverage/vxworks/modules/src/ut-osshell.c
  src/unit-test-coverage/vxworks/src/coveragetest-osfileapi.c
  src/unit-test-coverage/vxworks/src/coveragetest-osshell.c
Labels: CCB - 20200415, IC - 20200415, code reviewed

#415 Fix #366, Deprecated exception handling APIs
  src/os/inc/osapi-os-core.h
  src/os/posix/osapi.c
  src/os/rtems/osapi.c
  src/os/shared/os-impl.h
  src/os/shared/osapi-fpu.c
  src/os/vxworks/osapi.c
  src/unit-test-coverage/posix/src/coveragetest-osapi.c
  src/unit-test-coverage/shared/src/coveragetest-fpu.c
  src/unit-test-coverage/ut-stubs/src/osapi-base-impl-stubs.c
  src/unit-test-coverage/vxworks/src/coveragetest-osapi.c
  src/unit-tests/oscore-test/CMakeLists.txt
  src/unit-tests/oscore-test/ut_oscore_exception_test.c
  src/unit-tests/oscore-test/ut_oscore_exception_test.h
  src/unit-tests/oscore-test/ut_oscore_interrupt_test.h
  src/unit-tests/oscore-test/ut_oscore_test.c
  src/unit-tests/oscore-test/ut_oscore_test.h
  src/ut-stubs/osapi-utstub-fpu.c
Labels: CCB - 20200415, IC - 20200415, code reviewed, enhancement

#422 Fix #413, Add reference to osal user's guide from ReadMe
  README.md
Labels: CCB - 20200422, CCB - Fast Track, IC - 20200415, code reviewed, docs

#436 Fix #432, Infer OSAL_SYSTEM_OSTYPE from OSAL_SYSTEM_BSPTYPE
  CMakeLists.txt
  src/bsp/mcp750-vxworks/CMakeLists.txt
  src/bsp/pc-linux/CMakeLists.txt
  src/bsp/pc-rtems/CMakeLists.txt
Labels: CCB - 20200422, CCB - Fast Track, IC - 20200415, code reviewed, enhancement

#433 Integration Candidate: 2020-04-15
  CMakeLists.txt
  README.md
  src/bsp/mcp750-vxworks/CMakeLists.txt
  src/bsp/mcp750-vxworks/config/osconfig.h
  src/bsp/pc-linux/CMakeLists.txt
  src/bsp/pc-linux/config/osconfig.h
  src/bsp/pc-rtems/CMakeLists.txt
  src/bsp/pc-rtems/config/osconfig.h
  src/os/inc/osapi-os-core.h
  src/os/inc/osapi-os-filesys.h
  src/os/inc/osapi-os-net.h
  src/os/inc/osapi-os-timer.h
  src/os/inc/osapi-version.h
  src/os/inc/osapi.h
  src/os/portable/os-impl-no-shell.c
  src/os/posix/CMakeLists.txt
  src/os/posix/osapi.c
  src/os/posix/osfileapi.c
  src/os/posix/osshell.c
  src/os/posix/ostimer.c
  src/os/rtems/CMakeLists.txt
  src/os/rtems/osapi.c
  src/os/rtems/osfileapi.c
  src/os/rtems/osshell.c
  src/os/shared/os-impl.h
  src/os/shared/osapi-common.c
  src/os/shared/osapi-fpu.c
  src/os/shared/osapi-select.c
  src/os/vxworks/CMakeLists.txt
  src/os/vxworks/osapi.c
  src/os/vxworks/osfileapi.c
  src/os/vxworks/osshell.c
  src/tests/file-api-test/file-api-test.c
  src/unit-test-coverage/posix/src/coveragetest-osapi.c
  src/unit-test-coverage/shared/src/coveragetest-common.c
  src/unit-test-coverage/shared/src/coveragetest-fpu.c
  src/unit-test-coverage/ut-stubs/src/osapi-base-impl-stubs.c
  src/unit-test-coverage/vxworks/CMakeLists.txt
  src/unit-test-coverage/vxworks/modules/src/ut-osshell.c
  src/unit-test-coverage/vxworks/src/coveragetest-osapi.c
  src/unit-test-coverage/vxworks/src/coveragetest-osfileapi.c
  src/unit-test-coverage/vxworks/src/coveragetest-osshell.c
  src/unit-tests/oscore-test/CMakeLists.txt
  src/unit-tests/oscore-test/ut_oscore_exception_test.c
  src/unit-tests/oscore-test/ut_oscore_exception_test.h
  src/unit-tests/oscore-test/ut_oscore_select_test.c
  src/unit-tests/oscore-test/ut_oscore_select_test.h
  src/unit-tests/oscore-test/ut_oscore_test.c
  src/unit-tests/oscore-test/ut_oscore_test.h
  src/unit-tests/ostimer-test/ut_ostimer_timerio_test.c
  src/ut-stubs/osapi-utstub-fpu.c
Labels: IC - 20200415

#428 Fix #425, Correct Test_OS_ConvertToArrayIndex assertion typo
  src/unit-test-coverage/shared/src/coveragetest-idmap.c
Labels: CCB-20200422, IC-20200422, code reviewed, unit testing

#403 Fix #346, Adds library build, functional, and coverage test to CI
  .travis.yml
Labels: CCB-20200422, IC-20200422, ci, code reviewed, enhancement

#426 Fix #424, Add looping wait for self exiting task
  src/tests/osal-core-test/osal-core-test.c
Labels: CCB-20200422, IC-20200422, code reviewed

#431 unit-tests/osloader-test: make modules always be built for the test
  src/unit-tests/osloader-test/CMakeLists.txt
Labels: CCB-20200422, IC-20200422, code reviewed

#423 Fix #344, Consistent directory entry size limit
  src/bsp/mcp750-vxworks/config/osconfig.h
  src/bsp/pc-linux/config/osconfig.h
  src/bsp/pc-rtems/config/osconfig.h
  src/os/inc/osapi-os-filesys.h
  src/os/portable/os-impl-posix-dirs.c
  src/os/portable/os-impl-posix-files.c
  src/os/portable/os-impl-posix-io.c
  src/os/posix/osfilesys.c
  src/os/rtems/osfileapi.c
  src/os/rtems/osfilesys.c
  src/os/rtems/osshell.c
  src/os/shared/osapi-dir.c
  src/os/shared/osapi-file.c
  src/os/shared/osapi-filesys.c
  src/os/vxworks/osfileapi.c
  src/os/vxworks/osfilesys.c
  src/os/vxworks/osshell.c
  src/tests/file-api-test/file-api-test.c
  src/unit-test-coverage/portable/coveragetest-posixfile.c
  src/unit-test-coverage/portable/coveragetest-posixio.c
  src/unit-test-coverage/shared/src/coveragetest-file.c
  src/unit-test-coverage/shared/src/coveragetest-filesys.c
  src/unit-test-coverage/vxworks/src/coveragetest-osfilesys.c
  src/unit-tests/osfile-test/ut_osfile_dirio_test.c
  src/unit-tests/osfile-test/ut_osfile_fileio_test.c
  src/unit-tests/osfile-test/ut_osfile_test.c
  src/unit-tests/osfilesys-test/ut_osfilesys_diskio_test.c
  src/ut-stubs/osapi-utstub-filesys.c
Labels: CCB-20200422, IC-20200422, code reviewed
