Repository nasa/osal, pull requests merged in 2020-05, with the labels that each got.

#440 Integration Candidate: 2020-04-22
  .travis.yml
  README.md
  src/bsp/mcp750-vxworks/config/osconfig.h
  src/bsp/pc-linux/config/osconfig.h
  src/bsp/pc-rtems/config/osconfig.h
  src/os/inc/osapi-os-filesys.h
  src/os/inc/osapi-version.h
  src/os/portable/os-impl-posix-dirs.c
  src/os/portable/os-impl-posix-files.c
  src/os/portable/os-impl-posix-io.c
  src/os/posix/osfilesys.c
  src/os/rtems/osfileapi.c
  src/os/rtems/osfilesys.c
  src/os/rtems/osshell.c
  src/os/shared/osapi-dir.c
  src/os/shared/osapi-file.c
  src/os/shared/osapi-filesys.c
  src/os/vxworks/osfileapi.c
  src/os/vxworks/osfilesys.c
  src/os/vxworks/osshell.c
  src/tests/file-api-test/file-api-test.c
  src/tests/osal-core-test/osal-core-test.c
  src/unit-test-coverage/portable/coveragetest-posixfile.c
  src/unit-test-coverage/portable/coveragetest-posixio.c
  src/unit-test-coverage/shared/src/coveragetest-file.c
  src/unit-test-coverage/shared/src/coveragetest-filesys.c
  src/unit-test-coverage/shared/src/coveragetest-idmap.c
  src/unit-test-coverage/vxworks/src/coveragetest-osfilesys.c
  src/unit-tests/osfile-test/ut_osfile_dirio_test.c
  src/unit-tests/osfile-test/ut_osfile_fileio_test.c
  src/unit-tests/osfile-test/ut_osfile_test.c
  src/unit-tests/osfilesys-test/ut_osfilesys_diskio_test.c
  src/unit-tests/osloader-test/CMakeLists.txt
  src/ut-stubs/osapi-utstub-filesys.c
Labels: IC-20200422

#446 Fix #437, Add new API for obtaining exception task ID
  src/os/inc/osapi-os-core.h
  src/os/posix/src/os-impl-tasks.c
  src/os/rtems/src/os-impl-tasks.c
  src/os/shared/inc/os-shared-task.h
  src/os/shared/src/osapi-task.c
  src/os/vxworks/src/os-impl-tasks.c
  src/unit-test-coverage/shared/src/coveragetest-task.c
  src/unit-test-coverage/ut-stubs/src/osapi-task-impl-stubs.c
  src/unit-test-coverage/vxworks/src/coveragetest-tasks.c
  src/ut-stubs/osapi-utstub-task.c
Labels: CCB-20200506, IC-20200429, code reviewed

#441 Fix #435, fix string manipulations to avoid warnings
  src/os/shared/inc/os-shared-filesys.h
  src/os/shared/src/osapi-filesys.c
  src/unit-tests/inc/ut_os_support.h
Labels: CCB-20200506, IC-20200429, code reviewed

#458 Integration Candidate COMBINED 2020-04-29 and 2020-05-06
  README.md
  src/os/inc/osapi-os-core.h
  src/os/inc/osapi-version.h
  src/os/posix/src/os-impl-tasks.c
  src/os/rtems/src/os-impl-tasks.c
  src/os/shared/inc/os-shared-filesys.h
  src/os/shared/inc/os-shared-task.h
  src/os/shared/src/osapi-filesys.c
  src/os/shared/src/osapi-task.c
  src/os/vxworks/src/os-impl-tasks.c
  src/unit-test-coverage/shared/src/coveragetest-task.c
  src/unit-test-coverage/ut-stubs/src/osapi-task-impl-stubs.c
  src/unit-test-coverage/vxworks/src/coveragetest-tasks.c
  src/unit-tests/inc/ut_os_support.h
  src/ut-stubs/osapi-utstub-task.c
Labels: IC-20200429

#448 Fix #235, add check against OS_MAX_QUEUE_DEPTH
  src/os/inc/osapi-os-core.h
  src/os/shared/src/osapi-queue.c
  src/unit-test-coverage/shared/src/coveragetest-queue.c
Labels: CCB-20200513, IC-20200513, code reviewed, enhancement

#477 Integration Candidate 2020-05-13
  README.md
  src/os/inc/osapi-os-core.h
  src/os/inc/osapi-version.h
  src/os/shared/src/osapi-queue.c
  src/unit-test-coverage/shared/src/coveragetest-queue.c
Labels: IC-20200513

#464 Fix #455, correct length of device_name in filesys
  src/os/shared/inc/os-shared-filesys.h
  src/os/shared/src/osapi-filesys.c
  src/unit-test-coverage/shared/src/coveragetest-filesys.c
Labels: CCB-20200520, IC-20200520, code reviewed, enhancement

#475 Fix #474, Add timecb global mutex
  src/os/posix/src/os-impl-idmap.c
  src/os/rtems/src/os-impl-idmap.c
  src/os/vxworks/src/os-impl-idmap.c
Labels: CCB-20200520, IC-20200520, bug, code reviewed

#469 Fix #293, Expand API for object queries
  src/os/inc/osapi-os-core.h
  src/os/shared/inc/os-shared-idmap.h
  src/os/shared/src/osapi-idmap.c
  src/os/shared/src/osapi-time.c
  src/tests/osal-core-test/osal-core-test.c
  src/unit-test-coverage/shared/src/coveragetest-idmap.c
  src/ut-stubs/osapi-utstub-idmap.c
Labels: CCB-20200520, enhancement

#468 Fix #450, add external source directory for OS/BSP
  CMakeLists.txt
Labels: CCB-20200520, IC-20200520, code reviewed, enhancement

#472 Fix #470, Binary sem task delete issues
  src/os/posix/src/os-impl-binsem.c
  src/tests/bin-sem-test/bin-sem-test.c
Labels: CCB-20200520, IC-20200520, bug, code reviewed

#451 Fix #447, Resolve doxygen warnings
  src/os/inc/osapi-os-filesys.h
  src/os/portable/os-impl-posix-gettime.c
Labels: CCB-20200520, IC-20200520, code reviewed, enhancement

#466 Fix #459, dynamically create RAM disk devices on RTEMS
  src/bsp/pc-rtems/src/bsp_start.c
  src/bsp/pc-rtems/src/pcrtems_bsp_internal.h
  src/os/rtems/src/os-impl-filesys.c
  src/unit-tests/osfile-test/ut_osfile_test.c
Labels: CCB-20200520, IC-20200520, code reviewed, enhancement

#465 Fix #457, provide BSP shutdown handler
  src/bsp/mcp750-vxworks/src/bsp_start.c
  src/bsp/pc-linux/src/bsp_start.c
  src/bsp/pc-rtems/src/bsp_start.c
  src/bsp/shared/inc/bsp-impl.h
  ut_assert/src/utbsp.c
Labels: CCB-20200520, IC-20200520, code reviewed, enhancement

#463 Fix #454, Better error translation on statvfs()
  src/os/rtems/src/os-impl-filesys.c
Labels: CCB-20200520, IC-20200520, code reviewed, enhancement

#439 Fix #374, Add Object Utility API functional tests
  src/tests/idmap-api-test/idmap-api-test.c
Labels: CCB-20200513, IC-20200520, code reviewed, enhancement, unit testing

#483 Hotfix #374 object utilitys missing functional api tests
  src/tests/idmap-api-test/idmap-api-test.c
Labels: CCB-Fast Track, IC-20200520

#478 Fix #476, add global lock/unlock wrapper
  src/os/posix/src/os-impl-idmap.c
  src/os/shared/inc/os-shared-idmap.h
  src/os/shared/src/osapi-binsem.c
  src/os/shared/src/osapi-countsem.c
  src/os/shared/src/osapi-dir.c
  src/os/shared/src/osapi-file.c
  src/os/shared/src/osapi-filesys.c
  src/os/shared/src/osapi-idmap.c
  src/os/shared/src/osapi-module.c
  src/os/shared/src/osapi-mutex.c
  src/os/shared/src/osapi-printf.c
  src/os/shared/src/osapi-queue.c
  src/os/shared/src/osapi-sockets.c
  src/os/shared/src/osapi-task.c
  src/os/shared/src/osapi-time.c
  src/os/shared/src/osapi-timebase.c
  src/unit-test-coverage/shared/src/coveragetest-idmap.c
  src/ut-stubs/osapi-utstub-idmap.c
Labels: CCB-20200520, IC-20200520, conflicts, enhancement

#461 Fix #367, 453, 456, 460, Deprecate OS_VolumeTable and other fixes
  CMakeLists.txt
  osconfig.h.in
  src/bsp/mcp750-vxworks/CMakeLists.txt
  src/bsp/mcp750-vxworks/build_options.cmake
  src/bsp/mcp750-vxworks/src/bsp_voltab.c
  src/bsp/pc-linux/CMakeLists.txt
  src/bsp/pc-linux/build_options.cmake
  src/bsp/pc-linux/src/bsp_start.c
  src/bsp/pc-linux/src/bsp_voltab.c
  src/bsp/pc-rtems/CMakeLists.txt
  src/bsp/pc-rtems/build_options.cmake
  src/bsp/pc-rtems/src/bsp_start.c
  src/bsp/pc-rtems/src/bsp_voltab.c
  src/bsp/pc-rtems/src/pcrtems_bsp_internal.h
  src/bsp/shared/inc/bsp-impl.h
  src/bsp/shared/src/bsp_default_voltab.c
  src/os/inc/osapi-os-filesys.h
  src/os/inc/osapi.h
  src/os/portable/os-impl-bsd-select.c
  src/os/posix/src/os-impl-filesys.c
  src/os/rtems/src/os-impl-filesys.c
  src/os/shared/inc/os-shared-filesys.h
  src/os/shared/inc/os-shared-select.h
  src/os/shared/src/osapi-filesys.c
  src/os/vxworks/src/os-impl-filesys.c
  src/tests/file-api-test/file-api-test.c
  src/unit-test-coverage/portable/src/coveragetest-bsd-select.c
  src/unit-test-coverage/shared/src/coveragetest-filesys.c
  src/unit-test-coverage/vxworks/src/coveragetest-filesys.c
  src/unit-tests/oscore-test/ut_oscore_select_test.c
  src/unit-tests/osfile-test/ut_osfile_dirio_test.h
  src/unit-tests/osfilesys-test/ut_osfilesys_diskio_test.c
  src/unit-tests/osfilesys-test/ut_osfilesys_diskio_test.h
  src/unit-tests/osloader-test/CMakeLists.txt
  src/unit-tests/osloader-test/ut_osloader_module_test.c
  src/unit-tests/osloader-test/ut_osloader_symtable_test.c
  src/unit-tests/osloader-test/ut_osloader_test.c
  src/unit-tests/osloader-test/ut_osloader_test_platforms.h
  src/ut-stubs/utstub-helpers.c
Labels: CCB-20200520, IC-20200520, code reviewed, enhancement
