Repository nasa/osal, pull requests merged in 2020-09, with the labels that each got.

#582 Integration Candidate: 2020-08-26
  CMakeLists.txt
  README.md
  src/bsp/shared/inc/bsp-impl.h
  src/bsp/shared/src/bsp_default_voltab.c
  src/os/inc/common_types.h
  src/os/inc/osapi-os-core.h
  src/os/inc/osapi-os-filesys.h
  src/os/inc/osapi-os-loader.h
  src/os/inc/osapi-version.h
  src/os/posix/CMakeLists.txt
  src/os/posix/src/os-impl-fpu.c
  src/os/posix/src/os-impl-interrupts.c
  src/os/posix/src/os-impl-tasks.c
  src/os/rtems/CMakeLists.txt
  src/os/rtems/src/os-impl-fpu.c
  src/os/rtems/src/os-impl-interrupts.c
  src/os/rtems/src/os-impl-tasks.c
  src/os/shared/inc/os-shared-dir.h
  src/os/shared/inc/os-shared-filesys.h
  src/os/shared/inc/os-shared-fpu.h
  src/os/shared/inc/os-shared-interrupts.h
  src/os/shared/src/osapi-dir.c
  src/os/shared/src/osapi-filesys.c
  src/os/shared/src/osapi-fpu.c
  src/os/shared/src/osapi-interrupts.c
  src/os/vxworks/CMakeLists.txt
  src/os/vxworks/src/os-impl-fpu.c
  src/os/vxworks/src/os-impl-interrupts.c
  src/os/vxworks/src/os-impl-tasks.c
  src/tests/file-api-test/file-api-test.c
  src/unit-test-coverage/shared/src/coveragetest-dir.c
  src/unit-test-coverage/ut-stubs/CMakeLists.txt
  src/unit-test-coverage/ut-stubs/src/osapi-fpu-impl-stubs.c
  src/ut-stubs/CMakeLists.txt
  src/ut-stubs/osapi-utstub-dir.c
  src/ut-stubs/osapi-utstub-fpu.c
  src/ut-stubs/osapi-utstub-interrupts.c
Labels: IC-20200826

#583 Fix #581, Use OS_MAX_TIMEBASES for max timer create unit test
  src/unit-tests/ostimer-test/ut_ostimer_timerio_test.c
Labels: CCB-FastTrack, dependency, unit testing

#579 Fix #537, Fail tests on startup and tear down failures
  ut_assert/src/utbsp.c
Labels: CCB-20200826, IC-20200902, enhancement

#595 Fix #589, promote OS_ObjectIdToArrayIndex to public API
  src/os/inc/osapi-os-core.h
  src/os/shared/inc/os-shared-idmap.h
  src/os/shared/src/osapi-idmap.c
Labels: CCB-20200909, IC-20200909, Public API, enhancement

#596 Integration Candidate: 2020-09-09
  README.md
  src/os/inc/osapi-os-core.h
  src/os/inc/osapi-version.h
  src/os/shared/inc/os-shared-idmap.h
  src/os/shared/src/osapi-idmap.c
  src/unit-test-coverage/ut-stubs/inc/OCS_sys_types.h
Labels: IC-20200909

#585 Fix #584, Set Revision to 99 for development builds
  src/os/inc/osapi-version.h
Labels: CCB-20200916, IC-20200916, cFS-Bootes

#600 Integration Candidate: 2020-09-16
  README.md
  src/os/inc/osapi-version.h
Labels: IC-20200916

#603 Fix #104, Remove OS_Tick2Micros and internalize OS_Milli2Ticks
  src/os/inc/osapi-os-core.h
  src/os/posix/src/os-impl-timebase.c
  src/os/rtems/src/os-impl-binsem.c
  src/os/rtems/src/os-impl-timebase.c
  src/os/shared/inc/os-shared-timebase.h
  src/os/shared/src/osapi-timebase.c
  src/os/vxworks/src/os-impl-binsem.c
  src/os/vxworks/src/os-impl-countsem.c
  src/os/vxworks/src/os-impl-queues.c
  src/os/vxworks/src/os-impl-tasks.c
  src/os/vxworks/src/os-impl-timebase.c
  src/unit-test-coverage/shared/src/coveragetest-timebase.c
  src/unit-test-coverage/vxworks/src/coveragetest-binsem.c
  src/unit-test-coverage/vxworks/src/coveragetest-countsem.c
  src/unit-test-coverage/vxworks/src/coveragetest-queues.c
  src/unit-test-coverage/vxworks/src/coveragetest-tasks.c
  src/unit-tests/oscore-test/ut_oscore_misc_test.c
  src/unit-tests/oscore-test/ut_oscore_misc_test.h
  src/unit-tests/oscore-test/ut_oscore_test.c
  src/ut-stubs/osapi-utstub-timebase.c
Labels: CCB-20200923, IC-20200923, enhancement, public-api, removed

#605 Fix #604, Add ut_assert address equal macro
  ut_assert/inc/utassert.h
Labels: CCB-20200923, CCB-FastTrack, IC-20200923, enhancement, unit-test

#607 Integration Candidate: 2020-09-23
  README.md
  src/os/inc/osapi-os-core.h
  src/os/inc/osapi-version.h
  src/os/posix/src/os-impl-timebase.c
  src/os/rtems/src/os-impl-binsem.c
  src/os/rtems/src/os-impl-timebase.c
  src/os/shared/inc/os-shared-timebase.h
  src/os/shared/src/osapi-timebase.c
  src/os/vxworks/src/os-impl-binsem.c
  src/os/vxworks/src/os-impl-countsem.c
  src/os/vxworks/src/os-impl-queues.c
  src/os/vxworks/src/os-impl-tasks.c
  src/os/vxworks/src/os-impl-timebase.c
  src/unit-test-coverage/shared/src/coveragetest-timebase.c
  src/unit-test-coverage/vxworks/src/coveragetest-binsem.c
  src/unit-test-coverage/vxworks/src/coveragetest-countsem.c
  src/unit-test-coverage/vxworks/src/coveragetest-queues.c
  src/unit-test-coverage/vxworks/src/coveragetest-tasks.c
  src/unit-tests/oscore-test/ut_oscore_misc_test.c
  src/unit-tests/oscore-test/ut_oscore_misc_test.h
  src/unit-tests/oscore-test/ut_oscore_test.c
  src/ut-stubs/osapi-utstub-timebase.c
  ut_assert/inc/utassert.h
Labels: IC-20200923
