Repository nasa/osal, pull requests merged in 2020-08, with the labels that each got.

#489 Fix #379, Add FileSysAddFixedMap functional API test
  src/tests/file-sys-add-fixed-map-api-test/file-sys-add-fixed-map-api-test.c
Labels: CCB-20200812, code reviewed

#554 Fix #550, add function groups to ut assert
  ut_assert/inc/utlist.h
  ut_assert/inc/uttest.h
  ut_assert/src/utbsp.c
  ut_assert/src/utglobal.h
  ut_assert/src/utlist.c
  ut_assert/src/uttest.c
Labels: CCB-20200805, code reviewed

#549 fix #373, Add OSAL network APIs missing functional tests and fix #378 OS_TimedRead and OS_TimedWrite missing functional tests
  src/tests/network-api-test/network-api-test.c
Labels: CCB-20200805, IC-20200812, code reviewed

#563 Integration Candidate: 2020-08-12
  README.md
  src/os/inc/osapi-version.h
  src/tests/file-sys-add-fixed-map-api-test/file-sys-add-fixed-map-api-test.c
  src/tests/network-api-test/network-api-test.c
  ut_assert/inc/utlist.h
  ut_assert/inc/uttest.h
  ut_assert/src/utbsp.c
  ut_assert/src/utglobal.h
  ut_assert/src/utlist.c
  ut_assert/src/uttest.c
Labels: IC-20200812

#558 Fix #557, remove OS_ObjectIdMap/Unmap prototype and stub
  src/os/shared/inc/os-shared-idmap.h
  src/ut-stubs/osapi-utstub-idmap.c
Labels: CCB-20200819, CCB-READY, IC-20200819, code reviewed

#566 Fix #565, propagate return code from OS_TaskRegister_Impl()
  src/os/shared/src/osapi-task.c
Labels: CCB-20200819, CCB-READY, IC-20200819, code reviewed

#576 Integration Candidate: 2020-08-19
  README.md
  src/os/inc/osapi-version.h
  src/os/shared/inc/os-shared-idmap.h
  src/os/shared/src/osapi-binsem.c
  src/os/shared/src/osapi-countsem.c
  src/os/shared/src/osapi-dir.c
  src/os/shared/src/osapi-file.c
  src/os/shared/src/osapi-idmap.c
  src/os/shared/src/osapi-module.c
  src/os/shared/src/osapi-mutex.c
  src/os/shared/src/osapi-queue.c
  src/os/shared/src/osapi-task.c
  src/os/shared/src/osapi-time.c
  src/os/shared/src/osapi-timebase.c
  src/unit-test-coverage/shared/src/coveragetest-task.c
  src/ut-stubs/osapi-utstub-idmap.c
Labels: IC-20200819

#562 Fix #561, remove all deprecated code
  CMakeLists.txt
  src/bsp/shared/inc/bsp-impl.h
  src/bsp/shared/src/bsp_default_voltab.c
  src/os/inc/common_types.h
  src/os/inc/osapi-os-core.h
  src/os/inc/osapi-os-filesys.h
  src/os/inc/osapi-os-loader.h
  src/os/posix/CMakeLists.txt
  src/os/posix/src/os-impl-fpu.c
  src/os/posix/src/os-impl-interrupts.c
  src/os/posix/src/os-impl-tasks.c
  src/os/rtems/CMakeLists.txt
  src/os/rtems/src/os-impl-fpu.c
  src/os/rtems/src/os-impl-interrupts.c
  src/os/rtems/src/os-impl-tasks.c
  src/os/shared/inc/os-shared-dir.h
  src/os/shared/inc/os-shared-filesys.h
  src/os/shared/inc/os-shared-fpu.h
  src/os/shared/inc/os-shared-interrupts.h
  src/os/shared/src/osapi-dir.c
  src/os/shared/src/osapi-filesys.c
  src/os/shared/src/osapi-fpu.c
  src/os/shared/src/osapi-interrupts.c
  src/os/vxworks/CMakeLists.txt
  src/os/vxworks/src/os-impl-fpu.c
  src/os/vxworks/src/os-impl-interrupts.c
  src/os/vxworks/src/os-impl-tasks.c
  src/tests/file-api-test/file-api-test.c
  src/unit-test-coverage/shared/src/coveragetest-dir.c
  src/unit-test-coverage/ut-stubs/CMakeLists.txt
  src/unit-test-coverage/ut-stubs/src/osapi-fpu-impl-stubs.c
  src/ut-stubs/CMakeLists.txt
  src/ut-stubs/osapi-utstub-dir.c
  src/ut-stubs/osapi-utstub-fpu.c
  src/ut-stubs/osapi-utstub-interrupts.c
Labels: CCB-20200819, CCB: Needs Splinter, IC-20200826, code reviewed
