Repository nasa/osal, pull requests merged in 2020-10, with the labels that each got.

#541 Fix #540, add event callback framework
  src/os/inc/osapi-os-core.h
  src/os/shared/inc/os-shared-common.h
  src/os/shared/src/osapi-common.c
  src/os/shared/src/osapi-idmap.c
  src/os/shared/src/osapi-task.c
  src/ut-stubs/osapi-utstub-common.c
Labels: CCB-20200715, CCB-20200923, CCB-20200930, IC-20201007, cFS-Caelum

#616 Fix #615, RTEMS build issues
  src/os/rtems/src/os-impl-binsem.c
  src/os/rtems/src/os-impl-countsem.c
  src/os/rtems/src/os-impl-queues.c
  src/os/rtems/src/os-impl-tasks.c
Labels: CCB-FastTrack, CCB-READY, IC-20201007

#612 Integration Candidate: 2020-10-07
  README.md
  src/os/inc/osapi-os-core.h
  src/os/inc/osapi-version.h
  src/os/rtems/src/os-impl-binsem.c
  src/os/rtems/src/os-impl-countsem.c
  src/os/rtems/src/os-impl-queues.c
  src/os/rtems/src/os-impl-tasks.c
  src/os/shared/inc/os-shared-common.h
  src/os/shared/src/osapi-common.c
  src/os/shared/src/osapi-idmap.c
  src/os/shared/src/osapi-task.c
  src/ut-stubs/osapi-utstub-common.c
Labels: IC-20201007

#619 Fix #618, Use osal_id_t in RTEMS implementation
  src/os/rtems/src/os-impl-binsem.c
  src/os/rtems/src/os-impl-console.c
  src/os/rtems/src/os-impl-countsem.c
  src/os/rtems/src/os-impl-mutex.c
  src/os/rtems/src/os-impl-queues.c
  src/os/rtems/src/os-impl-tasks.c
  src/os/rtems/src/os-impl-timebase.c
Labels: CCB-20201007, IC-20201013

#617 Fix #556, Deprecate OS_open and OS_creat
  src/os/inc/osapi-os-filesys.h
  src/os/shared/src/osapi-file.c
  src/tests/file-api-test/file-api-test.c
  src/unit-test-coverage/shared/src/coveragetest-file.c
  src/unit-tests/oscore-test/ut_oscore_select_test.c
  src/unit-tests/osfile-test/ut_osfile_dirio_test.c
  src/unit-tests/osfile-test/ut_osfile_fileio_test.c
  src/ut-stubs/osapi-utstub-file.c
Labels: CCB-20201007, IC-20201013

#621 Integration candidate 2020-10-13
  README.md
  src/os/inc/osapi-os-filesys.h
  src/os/inc/osapi-version.h
  src/os/rtems/src/os-impl-binsem.c
  src/os/rtems/src/os-impl-console.c
  src/os/rtems/src/os-impl-countsem.c
  src/os/rtems/src/os-impl-mutex.c
  src/os/rtems/src/os-impl-queues.c
  src/os/rtems/src/os-impl-tasks.c
  src/os/rtems/src/os-impl-timebase.c
  src/os/shared/src/osapi-file.c
  src/tests/file-api-test/file-api-test.c
  src/unit-test-coverage/shared/src/coveragetest-file.c
  src/unit-tests/oscore-test/ut_oscore_select_test.c
  src/unit-tests/osfile-test/ut_osfile_dirio_test.c
  src/unit-tests/osfile-test/ut_osfile_fileio_test.c
  src/ut-stubs/osapi-utstub-file.c
Labels: IC-20201013

#587 Apply #585 to Bootes, Set Revision to 99 for development build
  src/os/inc/osapi-version.h
Labels: backport

#634 Fix #623, add debug messages for mutex double locks
  src/os/shared/inc/os-shared-mutex.h
  src/os/shared/src/osapi-mutex.c
Labels: CCB-20201028, IC-20201103
