Repository nasa/osal, pull requests merged in 2020-12, with the labels that each got.

#646 Fix #559, Rename set force fail
  src/unit-test-coverage/portable/src/coveragetest-bsd-select.c
  src/unit-test-coverage/portable/src/coveragetest-posix-files.c
  src/unit-test-coverage/portable/src/coveragetest-posix-gettime.c
  src/unit-test-coverage/portable/src/coveragetest-posix-io.c
  src/unit-test-coverage/shared/src/coveragetest-binsem.c
  src/unit-test-coverage/shared/src/coveragetest-common.c
  src/unit-test-coverage/shared/src/coveragetest-countsem.c
  src/unit-test-coverage/shared/src/coveragetest-file.c
  src/unit-test-coverage/shared/src/coveragetest-filesys.c
  src/unit-test-coverage/shared/src/coveragetest-idmap.c
  src/unit-test-coverage/shared/src/coveragetest-module.c
  src/unit-test-coverage/shared/src/coveragetest-mutex.c
  src/unit-test-coverage/shared/src/coveragetest-network.c
  src/unit-test-coverage/shared/src/coveragetest-printf.c
  src/unit-test-coverage/shared/src/coveragetest-queue.c
  src/unit-test-coverage/shared/src/coveragetest-select.c
  src/unit-test-coverage/shared/src/coveragetest-sockets.c
  src/unit-test-coverage/shared/src/coveragetest-task.c
  src/unit-test-coverage/shared/src/coveragetest-time.c
  src/unit-test-coverage/shared/src/coveragetest-timebase.c
  src/unit-test-coverage/vxworks/src/coveragetest-binsem.c
  src/unit-test-coverage/vxworks/src/coveragetest-common.c
  src/unit-test-coverage/vxworks/src/coveragetest-console.c
  src/unit-test-coverage/vxworks/src/coveragetest-countsem.c
  src/unit-test-coverage/vxworks/src/coveragetest-dirs.c
  src/unit-test-coverage/vxworks/src/coveragetest-filesys.c
  src/unit-test-coverage/vxworks/src/coveragetest-heap.c
  src/unit-test-coverage/vxworks/src/coveragetest-idmap.c
  src/unit-test-coverage/vxworks/src/coveragetest-loader.c
  src/unit-test-coverage/vxworks/src/coveragetest-mutex.c
  src/unit-test-coverage/vxworks/src/coveragetest-network.c
  src/unit-test-coverage/vxworks/src/coveragetest-no-module.c
  src/unit-test-coverage/vxworks/src/coveragetest-queues.c
  src/unit-test-coverage/vxworks/src/coveragetest-shell.c
  src/unit-test-coverage/vxworks/src/coveragetest-symtab.c
  src/unit-test-coverage/vxworks/src/coveragetest-tasks.c
  src/unit-test-coverage/vxworks/src/coveragetest-timebase.c
  ut_assert/inc/utstubs.h
  ut_assert/src/utstubs.c
Labels: CCB-20201112

#656 Fix #655, use 3 argument form of open
  src/os/portable/os-impl-posix-files.c
Labels: CCB-20201118, CCB-FastTrack, IC-20201124

#658 Fix #651, use unsigned types in VxWorks stack calculation
  src/os/vxworks/inc/os-impl-tasks.h
  src/os/vxworks/src/os-impl-tasks.c
Labels: CCB-20201118, IC-20201124

#653 Fix #586, Add one shot timer functional test
  src/tests/timer-test/timer-test.c
Labels: CCB-20201112, IC-20201124

#661 Fix #608 - Add RTEMS 5.x support
  src/bsp/pc-rtems/CMakeLists.txt
  src/bsp/pc-rtems/src/bsp_start.c
  src/bsp/pc-rtems/src/pcrtems_bsp_internal.h
  src/os/rtems/inc/os-rtems.h
  src/os/rtems/src/os-impl-heap.c
  src/os/rtems/src/os-impl-loader.c
Labels: CCB-20201202, IC-20201209

#663 fix #650 OS_chmod uses read or write access.
  src/os/portable/os-impl-posix-files.c
Labels: CCB-20201202, IC-20201208

#665 Fix #631, Add new functional tests for OS_chmod
  src/tests/file-api-test/file-api-test.c
Labels: CCB-20201202, IC-20201208, dependency

#667 Fix #120, Exit console loop on shutdown
  src/os/posix/src/os-impl-console.c
  src/os/rtems/src/os-impl-console.c
  src/os/vxworks/src/os-impl-console.c
Labels: CCB-20201202, IC-20201208, conflicts, enhancement

#674 Fix #290, Remove obsolete printf tests
  src/unit-tests/osprintf-test/CMakeLists.txt
  src/unit-tests/osprintf-test/ut_osprintf.c
  src/unit-tests/osprintf-test/ut_osprintf.h
  src/unit-tests/osprintf-test/ut_osprintf_c.c
  src/unit-tests/osprintf-test/ut_osprintf_d.c
  src/unit-tests/osprintf-test/ut_osprintf_f.c
  src/unit-tests/osprintf-test/ut_osprintf_i.c
  src/unit-tests/osprintf-test/ut_osprintf_ld.c
  src/unit-tests/osprintf-test/ut_osprintf_lf.c
  src/unit-tests/osprintf-test/ut_osprintf_li.c
  src/unit-tests/osprintf-test/ut_osprintf_lu.c
  src/unit-tests/osprintf-test/ut_osprintf_lx.c
  src/unit-tests/osprintf-test/ut_osprintf_lx_uc.c
  src/unit-tests/osprintf-test/ut_osprintf_misc.c
  src/unit-tests/osprintf-test/ut_osprintf_offset.c
  src/unit-tests/osprintf-test/ut_osprintf_offset.h
  src/unit-tests/osprintf-test/ut_osprintf_offset_dummy.c
  src/unit-tests/osprintf-test/ut_osprintf_p.c
  src/unit-tests/osprintf-test/ut_osprintf_printf.c
  src/unit-tests/osprintf-test/ut_osprintf_s.c
  src/unit-tests/osprintf-test/ut_osprintf_u.c
  src/unit-tests/osprintf-test/ut_osprintf_x.c
  src/unit-tests/osprintf-test/ut_osprintf_x_uc.c
Labels: CCB-20201202, CCB-20201209, CCB-FastTrack, IC-20201208

#671 Fix #670, clean up task definitions in core test
  src/tests/osal-core-test/osal-core-test.c
  src/tests/osal-core-test/osal-core-test.h
Labels: CCB-20201209, IC-20201215

#678 Fix #673 and #677, update global locks
  src/os/posix/src/os-impl-idmap.c
  src/os/rtems/src/os-impl-idmap.c
  src/os/shared/inc/os-shared-common.h
  src/os/shared/inc/os-shared-idmap.h
  src/os/shared/src/osapi-idmap.c
  src/unit-test-coverage/shared/src/coveragetest-idmap.c
  src/unit-test-coverage/ut-stubs/src/osapi-common-impl-stubs.c
Labels: CCB-20201209, conflicts

#687 Fix #686, Use errno in clock_getres error reporting
  src/os/posix/src/os-impl-timebase.c
Labels: CCB-20201216, IC-20201215, bug

#659 Fix #679, Add Markdown version of OSAL Configuration Guide
  doc/OSAL-Configuration-Guide.md
  doc/OSAL-Configuration-guide.doc
  doc/OSAL-Configuration-guide.pdf
Labels: CCB-20201216, IC-20201215

#682 Fix #569, Check and report sysconf error return
  src/os/posix/src/os-impl-tasks.c
Labels: CCB-20201216, IC-20201215

#681 Fix #542, Avoid UT failure if SEM_VALUE_MAX >= UINT32_MAX
  src/unit-tests/oscore-test/ut_oscore_countsem_test.c
Labels: CCB-20201216, IC-20201222

#683 Fix #377, Add "OSAL Select" functional tests
  src/tests/select-test/select-test.c
Labels: CCB-20201216

#689 Fix #688, implement value check and bug report macros
  default_config.cmake
  osconfig.h.in
  src/os/inc/osapi-error.h
  src/os/inc/osapi-macros.h
  src/os/inc/osapi.h
  src/os/shared/inc/os-shared-globaldefs.h
  src/os/shared/src/osapi-binsem.c
  src/os/shared/src/osapi-clock.c
  src/os/shared/src/osapi-common.c
  src/os/shared/src/osapi-countsem.c
  src/os/shared/src/osapi-dir.c
  src/os/shared/src/osapi-errors.c
  src/os/shared/src/osapi-file.c
  src/os/shared/src/osapi-filesys.c
  src/os/shared/src/osapi-heap.c
  src/os/shared/src/osapi-idmap.c
  src/os/shared/src/osapi-module.c
  src/os/shared/src/osapi-mutex.c
  src/os/shared/src/osapi-network.c
  src/os/shared/src/osapi-queue.c
  src/os/shared/src/osapi-select.c
  src/os/shared/src/osapi-shell.c
  src/os/shared/src/osapi-sockets.c
  src/os/shared/src/osapi-task.c
  src/os/shared/src/osapi-time.c
  src/os/shared/src/osapi-timebase.c
  src/tests/network-api-test/network-api-test.c
  src/tests/timer-add-api-test/timer-add-api-test.c
  src/unit-test-coverage/shared/src/coveragetest-binsem.c
  src/unit-test-coverage/shared/src/coveragetest-countsem.c
  src/unit-test-coverage/shared/src/coveragetest-filesys.c
  src/unit-test-coverage/shared/src/coveragetest-idmap.c
  src/unit-test-coverage/shared/src/coveragetest-module.c
  src/unit-test-coverage/shared/src/coveragetest-mutex.c
  src/unit-test-coverage/shared/src/coveragetest-network.c
  src/unit-test-coverage/shared/src/coveragetest-queue.c
  src/unit-test-coverage/shared/src/coveragetest-task.c
  src/unit-test-coverage/shared/src/coveragetest-time.c
  src/unit-test-coverage/shared/src/coveragetest-timebase.c
  src/unit-test-coverage/ut-stubs/inc/OCS_stdio.h
  src/unit-test-coverage/ut-stubs/inc/OCS_stdlib.h
  src/unit-test-coverage/ut-stubs/inc/OCS_string.h
  src/unit-test-coverage/ut-stubs/override_inc/stdio.h
  src/unit-test-coverage/ut-stubs/override_inc/stdlib.h
  src/unit-test-coverage/ut-stubs/override_inc/string.h
  src/unit-test-coverage/ut-stubs/src/libc-stdio-stubs.c
  src/unit-test-coverage/ut-stubs/src/libc-stdlib-stubs.c
  src/unit-test-coverage/ut-stubs/src/libc-string-stubs.c
  src/unit-tests/osnetwork-test/ut_osnetwork_misc_test.c
  src/unit-tests/ostimer-test/ut_ostimer_timerio_test.c
Labels: CCB-20201216, IC-20201222
