Repository nasa/osal, pull requests merged in 2020-03, with the labels that each got.

#369 IC 20200304
  src/os/rtems/osloader.c
Labels: CCB - 20200311, IC - 20200304

#371 Fix #364 and others, Scrub user's guide
  doc/OSAL Library API.doc
  doc/OSAL Library API.pdf
  src/os/inc/common_types.h
  src/os/inc/osapi-os-core.h
  src/os/inc/osapi-os-filesys.h
  src/os/inc/osapi-os-loader.h
  src/os/inc/osapi-os-net.h
  src/os/inc/osapi-os-timer.h
  src/os/inc/osapi-version.h
  src/os/inc/osapi.h
Labels: CCB - 20200318, IC - 20200318, code reviewed, docs, enhancement

#375 Integration Candidate 2020-03-18
  README.md
  doc/OSAL Library API.doc
  doc/OSAL Library API.pdf
  src/os/inc/common_types.h
  src/os/inc/osapi-os-core.h
  src/os/inc/osapi-os-filesys.h
  src/os/inc/osapi-os-loader.h
  src/os/inc/osapi-os-net.h
  src/os/inc/osapi-os-timer.h
  src/os/inc/osapi-version.h
  src/os/inc/osapi.h
Labels: IC - 20200318
