Repository nasa/osal, pull requests merged in 2020-07, with the labels that each got.

#490 Fix #196, Fix timer-test to be able to use OS_MAX_TIMERS value
  src/tests/timer-test/timer-test.c
Labels: CCB-20200624, IC-20200624, code reviewed

#523 Fix #522 - SocketOpen stub should set sock_id
  src/ut-stubs/osapi-utstub-sockets.c
Labels: CCB-20200624, IC-20200624, code reviewed, unit testing

#527 Fix #526, scrub OSAL stubs
  src/ut-stubs/osapi-utstub-binsem.c
  src/ut-stubs/osapi-utstub-clock.c
  src/ut-stubs/osapi-utstub-common.c
  src/ut-stubs/osapi-utstub-countsem.c
  src/ut-stubs/osapi-utstub-dir.c
  src/ut-stubs/osapi-utstub-errors.c
  src/ut-stubs/osapi-utstub-file.c
  src/ut-stubs/osapi-utstub-filesys.c
  src/ut-stubs/osapi-utstub-fpu.c
  src/ut-stubs/osapi-utstub-heap.c
  src/ut-stubs/osapi-utstub-idmap.c
  src/ut-stubs/osapi-utstub-interrupts.c
  src/ut-stubs/osapi-utstub-module.c
  src/ut-stubs/osapi-utstub-mutex.c
  src/ut-stubs/osapi-utstub-network.c
  src/ut-stubs/osapi-utstub-printf.c
  src/ut-stubs/osapi-utstub-queue.c
  src/ut-stubs/osapi-utstub-select.c
  src/ut-stubs/osapi-utstub-sockets.c
  src/ut-stubs/osapi-utstub-task.c
  src/ut-stubs/osapi-utstub-time.c
  src/ut-stubs/osapi-utstub-timebase.c
Labels: CCB-20200701, CCB-FastTrack, IC-20200624

#528 Fix #525, ensure POSIX stack size meets requirements
  src/os/posix/inc/os-posix.h
  src/os/posix/src/os-impl-tasks.c
Labels: CCB-20200701, CCB-FastTrack, IC-20200624

#535 Fix #534, adjust UT assert buffer sizes
  README.md
  ut_assert/src/utassert.c
Labels: CCB-FastTrack, CCB-READY, IC-20200624

#539 Fix #538, correct loop variable for coverage install
  src/unit-test-coverage/CMakeLists.txt
Labels: CCB-20200715, CCB-FastTrack, CCB-READY, IC-20200624

#536 Resolve #531, Add baseline and build number
  src/os/inc/osapi-version.h
Labels: CCB-FastTrack, IC-20200624

#548 fix #547 - ut_assert doc updates
  ut_assert/README.txt
  ut_assert/inc/utstubs.h
Labels: CCB-FastTrack, IC-20200624, docs, unit testing

#529 Integration Candidate: 2020-06-24
  README.md
  src/os/inc/osapi-version.h
  src/os/posix/inc/os-posix.h
  src/os/posix/src/os-impl-tasks.c
  src/tests/timer-test/timer-test.c
  src/unit-test-coverage/CMakeLists.txt
  src/ut-stubs/osapi-utstub-binsem.c
  src/ut-stubs/osapi-utstub-clock.c
  src/ut-stubs/osapi-utstub-common.c
  src/ut-stubs/osapi-utstub-countsem.c
  src/ut-stubs/osapi-utstub-dir.c
  src/ut-stubs/osapi-utstub-errors.c
  src/ut-stubs/osapi-utstub-file.c
  src/ut-stubs/osapi-utstub-filesys.c
  src/ut-stubs/osapi-utstub-fpu.c
  src/ut-stubs/osapi-utstub-heap.c
  src/ut-stubs/osapi-utstub-idmap.c
  src/ut-stubs/osapi-utstub-interrupts.c
  src/ut-stubs/osapi-utstub-module.c
  src/ut-stubs/osapi-utstub-mutex.c
  src/ut-stubs/osapi-utstub-network.c
  src/ut-stubs/osapi-utstub-printf.c
  src/ut-stubs/osapi-utstub-queue.c
  src/ut-stubs/osapi-utstub-select.c
  src/ut-stubs/osapi-utstub-sockets.c
  src/ut-stubs/osapi-utstub-task.c
  src/ut-stubs/osapi-utstub-time.c
  src/ut-stubs/osapi-utstub-timebase.c
  ut_assert/README.txt
  ut_assert/inc/utstubs.h
  ut_assert/src/utassert.c
Labels: IC-20200624
