Repository nasa/osal, pull requests merged in 2021-01, with the labels that each got.

#728 Fix #726, Resolve user's guide generation warnings
  src/os/inc/osapi-bsp.h
  src/os/inc/osapi-idmap.h
Labels: CCB-FastTrack, Ic-2010105

#731 Fix #730, Suppress invalid redundantAssignment warning from cppcheck
  src/os/shared/src/osapi-idmap.c
Labels: CCB-FastTrack, IC-20210105

#713 Fix #574, Document UtAssert_Message parameters
  ut_assert/inc/utassert.h
Labels: CCB-FastTrack, IC-20210105, unit-test

#714 Fix #598, Correct UtAssert_ZERO description typo
  ut_assert/inc/utassert.h
Labels: CCB-FastTrack, docs, unit-test

#741 Fix #740, Re-add automated static code analysis
  .github/workflows/static-analysis.yml
Labels: CCB-FastTrack, IC-20210105

#721 Fix #707 change sem flush to solve race condition
  src/tests/select-test/select-test.c
Labels: CCB-FastTrack, IC-20210105

#736 Fix #712, Replace UT_OS_LOG with UtPrintf
  src/unit-tests/inc/ut_os_support.h
  src/unit-tests/oscore-test/ut_oscore_misc_test.c
  src/unit-tests/oscore-test/ut_oscore_task_test.c
  src/unit-tests/osfile-test/ut_osfile_fileio_test.c
  src/unit-tests/osfile-test/ut_osfile_test.c
  src/unit-tests/osnetwork-test/ut_osnetwork_misc_test.c
  src/unit-tests/ostimer-test/ut_ostimer_timerio_test.c
Labels: CCB-FastTrack, IC-20210105

#744 osal Integration Candidate: 2021-01-05
  .github/workflows/static-analysis.yml
  README.md
  src/os/inc/osapi-bsp.h
  src/os/inc/osapi-idmap.h
  src/os/inc/osapi-version.h
  src/os/shared/src/osapi-idmap.c
  src/tests/select-test/select-test.c
  src/unit-tests/inc/ut_os_support.h
  src/unit-tests/oscore-test/ut_oscore_misc_test.c
  src/unit-tests/oscore-test/ut_oscore_task_test.c
  src/unit-tests/osfile-test/ut_osfile_fileio_test.c
  src/unit-tests/osfile-test/ut_osfile_test.c
  src/unit-tests/osnetwork-test/ut_osnetwork_misc_test.c
  src/unit-tests/ostimer-test/ut_ostimer_timerio_test.c
  ut_assert/inc/utassert.h
Labels: IC-20210105

#710 Fix #708, chmod error handling
  src/os/portable/os-impl-posix-files.c
  src/unit-test-coverage/portable/src/coveragetest-posix-files.c
  src/unit-test-coverage/ut-stubs/inc/OCS_errno.h
  src/unit-test-coverage/ut-stubs/override_inc/errno.h
Labels: CCB-20210106, IC-20210112

#716 Fix #544, add pointer check
  src/os/shared/src/osapi-sockets.c
  src/unit-test-coverage/shared/src/coveragetest-sockets.c
Labels: CCB-20210106, IC-20210112

#717 Fix #573, add OS_FileSysStatVolume
  src/os/inc/osapi-filesys.h
  src/os/shared/inc/os-shared-filesys.h
  src/os/shared/src/osapi-filesys.c
  src/tests/file-api-test/file-api-test.c
  src/unit-test-coverage/shared/src/coveragetest-filesys.c
  src/unit-tests/osfilesys-test/ut_osfilesys_diskio_test.c
  src/unit-tests/osfilesys-test/ut_osfilesys_diskio_test.h
  src/unit-tests/osfilesys-test/ut_osfilesys_test.c
  src/ut-stubs/osapi-utstub-filesys.c
Labels: CCB-20210106, IC-20210112

#711 Fix #471, order of operations for delete all
  src/os/shared/src/osapi-common.c
Labels: CCB-20210106, IC-20210112

#709 Fix #580, improve FS_BASED mounts on VxWorks
  src/os/inc/osapi-filesys.h
  src/os/vxworks/src/os-impl-filesys.c
  src/unit-test-coverage/vxworks/src/coveragetest-filesys.c
Labels: CCB-20210106, dependency

#720 Fix #606, Resolve cast-align error in VxWorks OS_TaskGetId_Impl
  src/os/vxworks/src/os-impl-tasks.c
Labels: CCB-20210106, IC-20210112

#734 Fix #644, Remove alignment macros
  src/os/inc/common_types.h
Labels: CCB-20210106, IC-20210112

#706 Fix #697, use POSIX dir implementation on VxWorks6
  src/os/vxworks/CMakeLists.txt
  src/os/vxworks/inc/os-impl-dirs.h
  src/os/vxworks/src/os-impl-dirs.c
  src/unit-test-coverage/portable/src/coveragetest-posix-dirs.c
  src/unit-test-coverage/ut-stubs/inc/OCS_errno.h
  src/unit-test-coverage/ut-stubs/inc/OCS_fcntl.h
  src/unit-test-coverage/ut-stubs/override_inc/errno.h
  src/unit-test-coverage/ut-stubs/override_inc/fcntl.h
  src/unit-test-coverage/vxworks/CMakeLists.txt
Labels: CCB-20210106, IC-20210112

#733 Fix #732, change uint32 to size_t
  src/bsp/pc-rtems/src/bsp_console.c
  src/os/rtems/src/os-impl-network.c
  src/os/rtems/src/os-impl-queues.c
  src/os/rtems/src/os-impl-tasks.c
Labels: CCB-20210106, IC-20210112, dependency

#715 Fix #445, add pointer parameter checks
  src/os/shared/src/osapi-idmap.c
  src/os/shared/src/osapi-timebase.c
  src/unit-test-coverage/shared/src/coveragetest-idmap.c
  src/unit-test-coverage/shared/src/coveragetest-timebase.c
Labels: CCB-20210106, IC-20210112

#723 Fix #429, add OS_time_t access functions
  src/os/inc/osapi-clock.h
  src/os/inc/osapi-file.h
  src/os/portable/os-impl-posix-files.c
  src/os/portable/os-impl-posix-gettime.c
  src/os/shared/src/osapi-clock.c
  src/tests/timer-add-api-test/timer-add-api-test.c
  src/tests/timer-test/timer-test.c
  src/unit-test-coverage/portable/src/coveragetest-posix-files.c
  src/unit-test-coverage/portable/src/coveragetest-posix-gettime.c
  src/unit-test-coverage/shared/src/coveragetest-clock.c
  src/unit-test-coverage/ut-stubs/inc/OCS_stat.h
  src/unit-tests/oscore-test/ut_oscore_misc_test.c
  src/unit-tests/ostimer-test/ut_ostimer_test.c
  src/ut-stubs/osapi-utstub-clock.c
Labels: CCB-20210106, IC-20210112, conflicts

#756 Fix #755, resolve subtasks not ending on time
  src/tests/select-test/select-test.c
Labels: CCB-FastTrack, CCB-READY, IC-20210112

#748 Fix #699, format printf correctly
  src/tests/select-test/select-test.c
Labels: CCB:2021-01-13, CCB:FastTrack, IC:2021-01-19

#759 Fix #718, deprecate OS_fsBlocksFree and OS_fsBytesFree
  src/os/inc/osapi-filesys.h
  src/os/shared/src/osapi-filesys.c
  src/unit-test-coverage/shared/src/coveragetest-filesys.c
  src/unit-tests/osfilesys-test/ut_osfilesys_diskio_test.c
  src/unit-tests/osfilesys-test/ut_osfilesys_diskio_test.h
  src/unit-tests/osfilesys-test/ut_osfilesys_test.c
  src/ut-stubs/osapi-utstub-filesys.c
Labels: CCB:FastTrack, IC:2021-01-19

#696 Fix #743, Create OSAL Security Policy Markdown
  SECURITY.md
Labels: CCB-20210106, CCB:FastTrack, IC:2021-01-19, docs, security

#747 Fix #746, Add UtDebug message from OS_printf stub
  src/ut-stubs/osapi-utstub-printf.c
Labels: CCB:FastTrack, IC:2021-01-19

#751 Fix #577, Document nested tests not supported
  ut_assert/inc/uttest.h
Labels: CCB:FastTrack, IC:2021-01-19

#763 Fix #761, Terminate string in TestReadWriteLseek
  src/tests/file-api-test/file-api-test.c
Labels: CCB:FastTrack, IC:2021-01-19

#758 Fix #757, Read extern C in osapi.h to support C++ use
  src/os/inc/osapi.h
Labels: CCB:FastTrack, IC:2021-01-19

#725 Fix #724, #722, rename ut clear force fail
  src/unit-test-coverage/portable/src/coveragetest-posix-files.c
  src/unit-test-coverage/shared/src/coveragetest-binsem.c
  src/unit-test-coverage/shared/src/coveragetest-countsem.c
  src/unit-test-coverage/shared/src/coveragetest-file.c
  src/unit-test-coverage/shared/src/coveragetest-filesys.c
  src/unit-test-coverage/shared/src/coveragetest-idmap.c
  src/unit-test-coverage/shared/src/coveragetest-mutex.c
  src/unit-test-coverage/shared/src/coveragetest-queue.c
  src/unit-test-coverage/shared/src/coveragetest-select.c
  src/unit-test-coverage/shared/src/coveragetest-sockets.c
  src/unit-test-coverage/shared/src/coveragetest-task.c
  src/unit-test-coverage/shared/src/coveragetest-time.c
  src/unit-test-coverage/shared/src/coveragetest-timebase.c
  src/unit-test-coverage/vxworks/src/coveragetest-common.c
  src/unit-test-coverage/vxworks/src/coveragetest-console.c
  src/unit-test-coverage/vxworks/src/coveragetest-filesys.c
  src/unit-test-coverage/vxworks/src/coveragetest-idmap.c
  src/unit-test-coverage/vxworks/src/coveragetest-loader.c
  src/unit-test-coverage/vxworks/src/coveragetest-no-module.c
  src/unit-test-coverage/vxworks/src/coveragetest-symtab.c
  src/unit-test-coverage/vxworks/src/coveragetest-tasks.c
  src/unit-test-coverage/vxworks/src/coveragetest-timebase.c
  ut_assert/inc/utstubs.h
  ut_assert/src/utstubs.c
Labels: CCB-20210106

#694 Fix #591, add test teardown failure to test summary
  ut_assert/src/utassert.c
  ut_assert/src/utbsp.c
Labels: CCB:2021-01-13, IC:2021-01-19

#754 Fix #753, Remove UT_CheckForOpenSockets
  src/ut-stubs/utstub-helpers.c
  src/ut-stubs/utstub-helpers.h
Labels: CCB:2021-01-13, dependency

#749 Fix #685 change file create to use read write
  src/tests/file-api-test/file-api-test.c
Labels: CCB:2021-01-13, IC:2021-01-19

#739 Fix #692, fix or statements
  src/tests/network-api-test/network-api-test.c
Labels: CCB:2021-01-13, IC:2021-01-19

#695 Fix #229, mqueue functional test
  src/tests/queue-test/queue-test.c
Labels: CCB-20210106

#735 Fix #429, OS_time_t with single tick counter
  src/os/inc/osapi-clock.h
  src/unit-test-coverage/shared/src/coveragetest-clock.c
Labels: CCB:2021-01-13, IC:2021-01-19

#764 Fix #760, Install modules and clean up files for unit tests
  src/tests/file-api-test/file-api-test.c
  src/tests/select-test/select-test.c
  src/unit-tests/osfile-test/ut_osfile_fileio_test.c
  src/unit-tests/osloader-test/CMakeLists.txt
Labels: CCB:2021-01-21

#767 osal Integration candidate: 2021-01-19
  README.md
  SECURITY.md
  src/os/inc/osapi-clock.h
  src/os/inc/osapi-filesys.h
  src/os/inc/osapi-version.h
  src/os/inc/osapi.h
  src/os/shared/src/osapi-filesys.c
  src/tests/file-api-test/file-api-test.c
  src/tests/network-api-test/network-api-test.c
  src/tests/queue-test/queue-test.c
  src/tests/select-test/select-test.c
  src/unit-test-coverage/portable/src/coveragetest-posix-files.c
  src/unit-test-coverage/shared/src/coveragetest-binsem.c
  src/unit-test-coverage/shared/src/coveragetest-clock.c
  src/unit-test-coverage/shared/src/coveragetest-countsem.c
  src/unit-test-coverage/shared/src/coveragetest-file.c
  src/unit-test-coverage/shared/src/coveragetest-filesys.c
  src/unit-test-coverage/shared/src/coveragetest-idmap.c
  src/unit-test-coverage/shared/src/coveragetest-mutex.c
  src/unit-test-coverage/shared/src/coveragetest-queue.c
  src/unit-test-coverage/shared/src/coveragetest-select.c
  src/unit-test-coverage/shared/src/coveragetest-sockets.c
  src/unit-test-coverage/shared/src/coveragetest-task.c
  src/unit-test-coverage/shared/src/coveragetest-time.c
  src/unit-test-coverage/shared/src/coveragetest-timebase.c
  src/unit-test-coverage/vxworks/src/coveragetest-common.c
  src/unit-test-coverage/vxworks/src/coveragetest-console.c
  src/unit-test-coverage/vxworks/src/coveragetest-filesys.c
  src/unit-test-coverage/vxworks/src/coveragetest-idmap.c
  src/unit-test-coverage/vxworks/src/coveragetest-loader.c
  src/unit-test-coverage/vxworks/src/coveragetest-no-module.c
  src/unit-test-coverage/vxworks/src/coveragetest-symtab.c
  src/unit-test-coverage/vxworks/src/coveragetest-tasks.c
  src/unit-test-coverage/vxworks/src/coveragetest-timebase.c
  src/unit-tests/osfile-test/ut_osfile_fileio_test.c
  src/unit-tests/osfilesys-test/ut_osfilesys_diskio_test.c
  src/unit-tests/osfilesys-test/ut_osfilesys_diskio_test.h
  src/unit-tests/osfilesys-test/ut_osfilesys_test.c
  src/unit-tests/osloader-test/CMakeLists.txt
  src/ut-stubs/osapi-utstub-filesys.c
  src/ut-stubs/osapi-utstub-printf.c
  src/ut-stubs/utstub-helpers.c
  src/ut-stubs/utstub-helpers.h
  ut_assert/inc/utstubs.h
  ut_assert/inc/uttest.h
  ut_assert/src/utassert.c
  ut_assert/src/utbsp.c
  ut_assert/src/utstubs.c
Labels: IC:2021-01-19
