Repository nasa/osal, pull requests merged in 2021-09, with the labels that each got.

#1144 Fix #1143, Regex update in coverage enforcement to match .0
  .github/workflows/local_unit_test.yml
Labels: CCB:Approved, continuous-integration

#1142 Fix #1141, add typecast to memchr call
  src/os/shared/inc/os-shared-common.h
Labels: CCB:Approved

#1149 Fix #1148, Enable symbol api test and MIR dump too large
  src/tests/symbol-api-test/symbol-api-test.c
Labels: CCB:Approved

#1152 Fix #1151, MIR symbol too long or table to long for osloader test
  src/unit-tests/osloader-test/ut_osloader_symtable_test.c
Labels: CCB:Ready

#1155 Fix #1154, add bsp-specific configuration flag registry
  CMakeLists.txt
  src/bsp/shared/inc/bsp-impl.h
  src/bsp/shared/src/bsp_default_resourcecfg.c
  src/os/inc/osapi-bsp.h
  src/os/vxworks/src/os-impl-tasks.c
  src/ut-stubs/osapi-bsp-stubs.c
Labels: CCB:Ready
