Repository nasa/osal, pull requests merged in 2021-12, with the labels that each got.

#1191 osal Integration candidate: Caelum+dev1
  .github/workflows/local_unit_test.yml
  README.md
  src/os/inc/common_types.h
  src/os/inc/osapi-error.h
  src/os/inc/osapi-version.h
  src/os/portable/os-impl-posix-gettime.c
  src/unit-test-coverage/ut-stubs/src/vxworks-intLib-stubs.c
  ut_assert/scripts/generate_stubs.pl
Labels: community

#1112 Partial #1108, add typedef for OSAL status codes
  src/os/inc/common_types.h
  src/os/inc/osapi-error.h
Labels: CCB:Approved

#1168 Fix #1167, vxWorks intLib stub aliasing issue
  src/unit-test-coverage/ut-stubs/src/vxworks-intLib-stubs.c
Labels: CCB:Approved

#1178 Fix #1177 Rename OS_XXXTime to OS_XXXLocalTime in comments.
  src/os/portable/os-impl-posix-gettime.c
Labels: CCB:Approved, docs, community

#1180 Fix #1139, Remove extern in stub prototypes
  ut_assert/scripts/generate_stubs.pl
Labels: CCB:Approved, community

#1186 Fix #1183, Add Duplicate Check to Local Unit Test
  .github/workflows/local_unit_test.yml
Labels: CCB:Approved, continuous-integration
