Repository nasa/osal, pull requests merged in 2021-04, with the labels that each got.

#927 osal Integration candidate: 2021-03-30
  README.md
  src/examples/tasking-example/tasking-example.c
  src/os/inc/common_types.h
  src/os/inc/osapi-dir.h
  src/os/inc/osapi-error.h
  src/os/inc/osapi-select.h
  src/os/inc/osapi-task.h
  src/os/inc/osapi-version.h
  src/os/portable/os-impl-bsd-select.c
  src/os/portable/os-impl-posix-dirs.c
  src/os/shared/inc/os-shared-task.h
  src/os/shared/src/osapi-common.c
  src/os/shared/src/osapi-idmap.c
  src/os/shared/src/osapi-printf.c
  src/os/shared/src/osapi-queue.c
  src/os/shared/src/osapi-select.c
  src/os/shared/src/osapi-task.c
  src/os/vxworks/src/os-impl-console.c
  src/os/vxworks/src/os-impl-symtab.c
  src/os/vxworks/src/os-impl-tasks.c
  src/os/vxworks/src/os-impl-timebase.c
  src/tests/CMakeLists.txt
  src/tests/bin-sem-flush-test/bin-sem-flush-test.c
  src/tests/bin-sem-test/bin-sem-test.c
  src/tests/bin-sem-timeout-test/bin-sem-timeout-test.c
  src/tests/count-sem-test/count-sem-test.c
  src/tests/file-api-test/file-api-test.c
  src/tests/mutex-test/mutex-test.c
  src/tests/osal-core-test/osal-core-test.c
  src/tests/queue-test/queue-test.c
  src/tests/sem-speed-test/sem-speed-test.c
  src/unit-test-coverage/portable/src/coveragetest-bsd-sockets.c
  src/unit-test-coverage/shared/src/coveragetest-task.c
  src/unit-test-coverage/ut-stubs/src/arpa-inet-stubs.c
  src/unit-test-coverage/ut-stubs/src/osapi-select-impl-stubs.c
  src/unit-test-coverage/ut-stubs/src/sys-socket-stubs.c
  src/unit-test-coverage/vxworks/adaptors/inc/ut-adaptor-symtab.h
  src/unit-test-coverage/vxworks/adaptors/src/ut-adaptor-symtab.c
  src/unit-test-coverage/vxworks/src/coveragetest-symtab.c
  src/unit-tests/oscore-test/ut_oscore_task_test.c
  src/unit-tests/oscore-test/ut_oscore_test.c
  src/ut-stubs/osapi-utstub-task.c
Labels: IC:2021-03-30

#937 Fix #844, switch to use CLOCK_REALTIME
  src/os/portable/os-impl-posix-gettime.c
  src/os/posix/inc/os-impl-gettime.h
  src/os/rtems/inc/os-impl-gettime.h
  src/os/vxworks/inc/os-impl-gettime.h
Labels: CCB:Reviewed, IC:2021-04-06

#938 Fix #887, specify shell name in ShellOutputToFile
  src/os/vxworks/src/os-impl-shell.c
Labels: CCB:Reviewed, IC:2021-04-06

#941 Fix #871, allow OSAL re-initialization
  src/os/posix/src/os-impl-console.c
  src/os/rtems/src/os-impl-console.c
  src/os/shared/inc/os-shared-common.h
  src/os/shared/src/osapi-common.c
  src/os/shared/src/osapi-idmap.c
  src/os/shared/src/osapi-printf.c
  src/os/vxworks/src/os-impl-console.c
  src/unit-test-coverage/shared/src/coveragetest-common.c
  src/unit-test-coverage/shared/src/coveragetest-idmap.c
  src/unit-test-coverage/shared/src/coveragetest-printf.c
Labels: CCB:Reviewed, IC:2021-04-13

#948 Fix #944, add OS_API_Teardown
  src/os/inc/osapi-common.h
  src/os/shared/src/osapi-common.c
  src/tests/bin-sem-flush-test/bin-sem-flush-test.c
  src/tests/bin-sem-test/bin-sem-test.c
  src/tests/bin-sem-timeout-test/bin-sem-timeout-test.c
  src/tests/count-sem-test/count-sem-test.c
  src/tests/file-api-test/file-api-test.c
  src/tests/file-sys-add-fixed-map-api-test/file-sys-add-fixed-map-api-test.c
  src/tests/idmap-api-test/idmap-api-test.c
  src/tests/mutex-test/mutex-test.c
  src/tests/network-api-test/network-api-test.c
  src/tests/osal-core-test/osal-core-test.c
  src/tests/queue-test/queue-test.c
  src/tests/select-test/select-test.c
  src/tests/sem-speed-test/sem-speed-test.c
  src/tests/shell-test/shell-test.c
  src/tests/symbol-api-test/symbol-api-test.c
  src/tests/time-base-api-test/time-base-api-test.c
  src/tests/timer-add-api-test/timer-add-api-test.c
  src/tests/timer-test/timer-test.c
  src/unit-test-coverage/shared/src/coveragetest-common.c
  src/unit-tests/oscore-test/ut_oscore_test.c
  src/unit-tests/osfile-test/ut_osfile_test.c
  src/unit-tests/osfilesys-test/ut_osfilesys_test.c
  src/unit-tests/osloader-test/ut_osloader_test.c
  src/unit-tests/osnetwork-test/ut_osnetwork_test.c
  src/unit-tests/ostimer-test/ut_ostimer_test.c
Labels: CCB:Reviewed, IC:2021-04-13

#940 Fix #939, rework shell test
  src/tests/shell-test/shell-test.c
Labels: CCB:Reviewed, IC:2021-04-13

#956 osal Integration candidate: 2021-04-13
  README.md
  src/os/inc/osapi-common.h
  src/os/inc/osapi-version.h
  src/os/posix/src/os-impl-console.c
  src/os/rtems/src/os-impl-console.c
  src/os/shared/inc/os-shared-common.h
  src/os/shared/src/osapi-common.c
  src/os/shared/src/osapi-idmap.c
  src/os/shared/src/osapi-printf.c
  src/os/vxworks/src/os-impl-console.c
  src/tests/bin-sem-flush-test/bin-sem-flush-test.c
  src/tests/bin-sem-test/bin-sem-test.c
  src/tests/bin-sem-timeout-test/bin-sem-timeout-test.c
  src/tests/count-sem-test/count-sem-test.c
  src/tests/file-api-test/file-api-test.c
  src/tests/file-sys-add-fixed-map-api-test/file-sys-add-fixed-map-api-test.c
  src/tests/idmap-api-test/idmap-api-test.c
  src/tests/mutex-test/mutex-test.c
  src/tests/network-api-test/network-api-test.c
  src/tests/osal-core-test/osal-core-test.c
  src/tests/queue-test/queue-test.c
  src/tests/select-test/select-test.c
  src/tests/sem-speed-test/sem-speed-test.c
  src/tests/shell-test/shell-test.c
  src/tests/symbol-api-test/symbol-api-test.c
  src/tests/time-base-api-test/time-base-api-test.c
  src/tests/timer-add-api-test/timer-add-api-test.c
  src/tests/timer-test/timer-test.c
  src/unit-test-coverage/shared/src/coveragetest-common.c
  src/unit-test-coverage/shared/src/coveragetest-idmap.c
  src/unit-test-coverage/shared/src/coveragetest-printf.c
  src/unit-tests/oscore-test/ut_oscore_test.c
  src/unit-tests/osfile-test/ut_osfile_test.c
  src/unit-tests/osfilesys-test/ut_osfilesys_test.c
  src/unit-tests/osloader-test/ut_osloader_test.c
  src/unit-tests/osnetwork-test/ut_osnetwork_test.c
  src/unit-tests/ostimer-test/ut_ostimer_test.c
Labels: IC:2021-04-13

#950 Fix #932, Eliminate time and access name collisions with VxWorks
  src/os/inc/osapi-file.h
  src/os/portable/os-impl-posix-files.c
  src/os/portable/os-impl-posix-gettime.c
  src/os/shared/inc/os-shared-file.h
  src/os/shared/src/osapi-file.c
  src/unit-test-coverage/portable/src/coveragetest-posix-files.c
  src/unit-test-coverage/shared/src/coveragetest-file.c
  src/unit-test-coverage/ut-stubs/src/osapi-file-impl-stubs.c
  src/unit-tests/osfile-test/ut_osfile_fileio_test.c
  src/ut-stubs/osapi-utstub-file.c
Labels: CCB:Approved, IC:2021-04-27

#946 Fix #945, shell implementation on posix and rtems
  src/os/posix/src/os-impl-shell.c
  src/os/rtems/CMakeLists.txt
  src/os/rtems/src/os-impl-shell.c
Labels: CCB:2021-04-14, CCB:Approved

#967 osal Integration candidate: 2021-04-20
  README.md
  src/os/inc/osapi-file.h
  src/os/inc/osapi-version.h
  src/os/portable/os-impl-posix-files.c
  src/os/portable/os-impl-posix-gettime.c
  src/os/posix/src/os-impl-shell.c
  src/os/rtems/CMakeLists.txt
  src/os/rtems/src/os-impl-shell.c
  src/os/shared/inc/os-shared-file.h
  src/os/shared/src/osapi-file.c
  src/unit-test-coverage/portable/src/coveragetest-posix-files.c
  src/unit-test-coverage/shared/src/coveragetest-file.c
  src/unit-test-coverage/ut-stubs/src/osapi-file-impl-stubs.c
  src/unit-tests/osfile-test/ut_osfile_fileio_test.c
  src/ut-stubs/osapi-utstub-file.c
Labels: IC:2021-04-20

#972 Fix #970, update documentation for read/write
  src/os/inc/osapi-file.h
Labels: CCB:FastTrack, IC:2021-04-27

#953 Fix #419 #729 #954, Adds local makefile and bundle/local unit test actions with coverage verification
  .github/workflows/codeql-build.yml
  .github/workflows/local_unit_test.yml
  .gitignore
  Makefile.sample
  src/unit-test-coverage/portable/src/coveragetest-bsd-sockets.c
Labels: CCB:2021-04-14, IC:2021-04-27, build-system, continuous-integration, enhancement

#971 Fix #969, socket accept using incorrect record
  src/os/shared/src/osapi-sockets.c
  src/tests/network-api-test/network-api-test.c
Labels: CCB:FastTrack, CCB:Ready
