Repository nasa/osal, pull requests merged in 2021-05, with the labels that each got.

#973 Fix #964, UtPrintx function
  ut_assert/src/uttools.c
Labels: CCB:Approved

#976 Fix #960, add socket shutdown implementation
  src/os/inc/osapi-error.h
  src/os/inc/osapi-sockets.h
  src/os/portable/os-impl-bsd-sockets.c
  src/os/portable/os-impl-no-sockets.c
  src/os/posix/inc/os-impl-sockets.h
  src/os/shared/inc/os-shared-sockets.h
  src/os/shared/src/osapi-sockets.c
  src/tests/network-api-test/network-api-test.c
  src/unit-test-coverage/portable/src/coveragetest-bsd-sockets.c
  src/unit-test-coverage/portable/src/coveragetest-no-sockets.c
  src/unit-test-coverage/shared/src/coveragetest-sockets.c
  src/unit-test-coverage/ut-stubs/inc/OCS_sys_socket.h
  src/unit-test-coverage/ut-stubs/override_inc/sys/socket.h
  src/unit-test-coverage/ut-stubs/src/os-shared-sockets-impl-stubs.c
  src/unit-test-coverage/ut-stubs/src/sys-socket-stubs.c
  src/ut-stubs/osapi-sockets-stubs.c
Labels: CCB:Approved, IC:2021-05-04

#979 osal Integration candidate: 2021-05-04
  README.md
  src/os/inc/osapi-error.h
  src/os/inc/osapi-sockets.h
  src/os/inc/osapi-version.h
  src/os/portable/os-impl-bsd-sockets.c
  src/os/portable/os-impl-no-sockets.c
  src/os/posix/inc/os-impl-sockets.h
  src/os/shared/inc/os-shared-sockets.h
  src/os/shared/src/osapi-sockets.c
  src/tests/network-api-test/network-api-test.c
  src/unit-test-coverage/portable/src/coveragetest-bsd-sockets.c
  src/unit-test-coverage/portable/src/coveragetest-no-sockets.c
  src/unit-test-coverage/shared/src/coveragetest-sockets.c
  src/unit-test-coverage/ut-stubs/inc/OCS_sys_socket.h
  src/unit-test-coverage/ut-stubs/override_inc/sys/socket.h
  src/unit-test-coverage/ut-stubs/src/os-shared-sockets-impl-stubs.c
  src/unit-test-coverage/ut-stubs/src/sys-socket-stubs.c
  src/ut-stubs/osapi-sockets-stubs.c
  ut_assert/src/uttools.c
Labels: IC:2021-05-04

#978 Fix #640, configuration guide updates
  doc/OSAL-Configuration-Guide.md
Labels: CCB:Approved, IC:2021-05-11

#977 Fix #545, update OS_TaskCreate doc
  src/os/inc/osapi-task.h
Labels: CCB:Approved, CCB:FastTrack, IC:2021-05-11

#993 Fix #988, do not require nonblock mode
  src/os/portable/os-impl-bsd-sockets.c
  src/os/posix/inc/os-impl-sockets.h
  src/os/rtems/inc/os-impl-sockets.h
  src/os/vxworks/inc/os-impl-sockets.h
  src/tests/network-api-test/network-api-test.c
  src/unit-test-coverage/portable/src/coveragetest-bsd-sockets.c
Labels: CCB:FastTrack, CCB:Ready, IC:2021-05-11

#996 osal Integration candidate: 2021-05-11
  .github/workflows/static-analysis.yml
  README.md
  doc/OSAL-Configuration-Guide.md
  src/bsp/generic-linux/src/bsp_start.c
  src/bsp/generic-linux/src/generic_linux_bsp_internal.h
  src/bsp/generic-vxworks/src/bsp_start.c
  src/bsp/generic-vxworks/src/generic_vxworks_bsp_internal.h
  src/bsp/pc-rtems/src/bsp_start.c
  src/bsp/pc-rtems/src/pcrtems_bsp_internal.h
  src/bsp/shared/inc/bsp-impl.h
  src/os/inc/osapi-clock.h
  src/os/inc/osapi-common.h
  src/os/inc/osapi-dir.h
  src/os/inc/osapi-error.h
  src/os/inc/osapi-file.h
  src/os/inc/osapi-filesys.h
  src/os/inc/osapi-heap.h
  src/os/inc/osapi-idmap.h
  src/os/inc/osapi-module.h
  src/os/inc/osapi-network.h
  src/os/inc/osapi-queue.h
  src/os/inc/osapi-select.h
  src/os/inc/osapi-shell.h
  src/os/inc/osapi-sockets.h
  src/os/inc/osapi-task.h
  src/os/inc/osapi-timebase.h
  src/os/inc/osapi-timer.h
  src/os/inc/osapi-version.h
  src/os/portable/os-impl-bsd-sockets.c
  src/os/portable/os-impl-console-bsp.c
  src/os/posix/inc/os-impl-sockets.h
  src/os/rtems/inc/os-impl-sockets.h
  src/os/shared/src/osapi-debug.c
  src/os/shared/src/osapi-queue.c
  src/os/vxworks/inc/os-impl-sockets.h
  src/tests/network-api-test/network-api-test.c
  src/unit-test-coverage/portable/src/coveragetest-bsd-sockets.c
  src/unit-test-coverage/shared/src/coveragetest-errors.c
  src/unit-test-coverage/shared/src/coveragetest-file.c
  src/unit-test-coverage/shared/src/coveragetest-filesys.c
  src/unit-test-coverage/shared/src/coveragetest-idmap.c
  src/unit-test-coverage/shared/src/coveragetest-network.c
  src/unit-test-coverage/shared/src/coveragetest-select.c
  src/unit-test-coverage/shared/src/coveragetest-sockets.c
  src/unit-test-coverage/shared/src/coveragetest-time.c
  src/unit-test-coverage/shared/src/coveragetest-timebase.c
  src/unit-test-coverage/ut-stubs/inc/OCS_bsp-impl.h
  src/unit-test-coverage/ut-stubs/override_inc/bsp-impl.h
  src/unit-test-coverage/ut-stubs/src/bsp-console-impl-stubs.c
  ut_assert/inc/utassert.h
  ut_assert/inc/uttools.h
  ut_assert/src/utbsp.c
Labels: IC:2021-05-11

#985 Fix #983, rename hooks to handlers
  src/unit-test-coverage/ut-stubs/CMakeLists.txt
  src/unit-test-coverage/ut-stubs/src/os-shared-file-impl-handlers.c
  src/unit-test-coverage/ut-stubs/src/os-shared-filesys-impl-handlers.c
  src/unit-test-coverage/ut-stubs/src/os-shared-idmap-handlers.c
  src/unit-test-coverage/ut-stubs/src/os-shared-network-impl-handlers.c
  src/ut-stubs/CMakeLists.txt
  src/ut-stubs/osapi-binsem-handlers.c
  src/ut-stubs/osapi-clock-handlers.c
  src/ut-stubs/osapi-countsem-handlers.c
  src/ut-stubs/osapi-dir-handlers.c
  src/ut-stubs/osapi-error-handlers.c
  src/ut-stubs/osapi-file-handlers.c
  src/ut-stubs/osapi-filesys-handlers.c
  src/ut-stubs/osapi-heap-handlers.c
  src/ut-stubs/osapi-idmap-handlers.c
  src/ut-stubs/osapi-module-handlers.c
  src/ut-stubs/osapi-mutex-handlers.c
  src/ut-stubs/osapi-network-handlers.c
  src/ut-stubs/osapi-printf-handlers.c
  src/ut-stubs/osapi-queue-handlers.c
  src/ut-stubs/osapi-sockets-handlers.c
  src/ut-stubs/osapi-task-handlers.c
  src/ut-stubs/osapi-timebase-handlers.c
  src/ut-stubs/osapi-timer-handlers.c
  src/ut-stubs/osapi-version-handlers.c
  ut_assert/scripts/generate_stubs.pl
Labels: CCB:Approved, IC:2021-05-18

#1000 Fix #999, propagate status code in OS_rmdir
  src/os/shared/src/osapi-dir.c
Labels: CCB:Approved

#1003 Fix #1002, remove extra newlines in utassert logs
  ut_assert/src/utbsp.c
Labels: CCB:Approved, IC:2021-05-18

#1001 Fix #981, rework "unit-tests" to use macros
  src/unit-tests/inc/ut_os_support.h
  src/unit-tests/oscore-test/ut_oscore_binsem_test.c
  src/unit-tests/oscore-test/ut_oscore_countsem_test.c
  src/unit-tests/oscore-test/ut_oscore_misc_test.c
  src/unit-tests/oscore-test/ut_oscore_mutex_test.c
  src/unit-tests/oscore-test/ut_oscore_queue_test.c
  src/unit-tests/oscore-test/ut_oscore_select_test.c
  src/unit-tests/oscore-test/ut_oscore_select_test.h
  src/unit-tests/oscore-test/ut_oscore_task_test.c
  src/unit-tests/oscore-test/ut_oscore_test.c
  src/unit-tests/osfile-test/ut_osfile_dirio_test.c
  src/unit-tests/osfile-test/ut_osfile_fileio_test.c
  src/unit-tests/osfilesys-test/ut_osfilesys_diskio_test.c
  src/unit-tests/osloader-test/ut_osloader_module_test.c
  src/unit-tests/osloader-test/ut_osloader_symtable_test.c
  src/unit-tests/osnetwork-test/ut_osnetwork_misc_test.c
  src/unit-tests/ostimer-test/ut_ostimer_timerio_test.c
Labels: CCB:Approved

#812 Work #384, #640, #672, Minor fixes to osal config guide
  doc/OSAL-Configuration-Guide.md
Labels: IC:2021-05-18, community, docs, squash

#990 Fix #982, Add test for object id inline functions
  src/os/shared/inc/os-shared-idmap.h
  src/os/shared/src/osapi-idmap.c
  src/unit-test-coverage/shared/src/coveragetest-idmap.c
Labels: CCB:Approved

#998 Fix #994, fixed invalid inputs for OS_mkdir
  src/tests/file-api-test/file-api-test.c
  src/unit-test-coverage/shared/src/coveragetest-dir.c
  src/unit-tests/osfile-test/ut_osfile_dirio_test.c
Labels: CCB:Approved, IC:2021-05-18

#987 Fix #986, Show CodeQL Preview
  .github/workflows/codeql-osal-default.yml
Labels: CCB:Approved, continuous-integration

#1006 osal Integration candidate: 2021-05-18
  .github/workflows/codeql-osal-default.yml
  README.md
  doc/OSAL-Configuration-Guide.md
  src/os/inc/osapi-version.h
  src/os/shared/inc/os-shared-idmap.h
  src/os/shared/src/osapi-dir.c
  src/os/shared/src/osapi-idmap.c
  src/tests/file-api-test/file-api-test.c
  src/unit-test-coverage/shared/src/coveragetest-dir.c
  src/unit-test-coverage/shared/src/coveragetest-idmap.c
  src/unit-test-coverage/ut-stubs/CMakeLists.txt
  src/unit-test-coverage/ut-stubs/src/os-shared-file-impl-handlers.c
  src/unit-test-coverage/ut-stubs/src/os-shared-filesys-impl-handlers.c
  src/unit-test-coverage/ut-stubs/src/os-shared-idmap-handlers.c
  src/unit-test-coverage/ut-stubs/src/os-shared-network-impl-handlers.c
  src/unit-tests/inc/ut_os_support.h
  src/unit-tests/oscore-test/ut_oscore_binsem_test.c
  src/unit-tests/oscore-test/ut_oscore_countsem_test.c
  src/unit-tests/oscore-test/ut_oscore_misc_test.c
  src/unit-tests/oscore-test/ut_oscore_mutex_test.c
  src/unit-tests/oscore-test/ut_oscore_queue_test.c
  src/unit-tests/oscore-test/ut_oscore_select_test.c
  src/unit-tests/oscore-test/ut_oscore_select_test.h
  src/unit-tests/oscore-test/ut_oscore_task_test.c
  src/unit-tests/oscore-test/ut_oscore_test.c
  src/unit-tests/osfile-test/ut_osfile_dirio_test.c
  src/unit-tests/osfile-test/ut_osfile_fileio_test.c
  src/unit-tests/osfilesys-test/ut_osfilesys_diskio_test.c
  src/unit-tests/osloader-test/ut_osloader_module_test.c
  src/unit-tests/osloader-test/ut_osloader_symtable_test.c
  src/unit-tests/osnetwork-test/ut_osnetwork_misc_test.c
  src/unit-tests/ostimer-test/ut_ostimer_timerio_test.c
  src/ut-stubs/CMakeLists.txt
  src/ut-stubs/osapi-binsem-handlers.c
  src/ut-stubs/osapi-clock-handlers.c
  src/ut-stubs/osapi-countsem-handlers.c
  src/ut-stubs/osapi-dir-handlers.c
  src/ut-stubs/osapi-error-handlers.c
  src/ut-stubs/osapi-file-handlers.c
  src/ut-stubs/osapi-filesys-handlers.c
  src/ut-stubs/osapi-heap-handlers.c
  src/ut-stubs/osapi-idmap-handlers.c
  src/ut-stubs/osapi-module-handlers.c
  src/ut-stubs/osapi-mutex-handlers.c
  src/ut-stubs/osapi-network-handlers.c
  src/ut-stubs/osapi-printf-handlers.c
  src/ut-stubs/osapi-queue-handlers.c
  src/ut-stubs/osapi-sockets-handlers.c
  src/ut-stubs/osapi-task-handlers.c
  src/ut-stubs/osapi-timebase-handlers.c
  src/ut-stubs/osapi-timer-handlers.c
  src/ut-stubs/osapi-version-handlers.c
  ut_assert/scripts/generate_stubs.pl
  ut_assert/src/utbsp.c
Labels: IC:2021-05-18, community

#1026 Fix #991, Add count sem timeout test
  src/tests/count-sem-timeout-test/count-sem-timeout-test.c
Labels: CCB:Approved, IC:021-05-25

#1050 osal Integration candidate: 2021-05-25
  README.md
  src/bsp/generic-linux/src/bsp_start.c
  src/bsp/generic-linux/src/generic_linux_bsp_internal.h
  src/os/inc/osapi-version.h
  src/os/shared/src/osapi-task.c
  src/tests/count-sem-timeout-test/count-sem-timeout-test.c
  src/unit-test-coverage/shared/src/coveragetest-task.c
Labels: IC:2021-05-25

#1033 Fix #913, include doxygen targets locally
  CMakeLists.txt
  doc/src/CMakeLists.txt
  doc/src/osal-apiguide.doxyfile.in
  doc/src/osal-common.doxyfile.in
  doc/src/osal_fs.dox
  doc/src/osal_timer.dox
  doc/src/osalmain.dox
Labels: CCB:Approved

#1031 Fix #984, Document OS_ObjectIdToArrayIndex as public
  src/os/shared/src/osapi-idmap.c
Labels: CCB:Approved, CCB:FastTrack, IC:2021-06-01
