Repository nasa/osal, pull requests merged in 2021-07, with the labels that each got.

#1081 Fix #1080, add range to OS_TaskDelay checks
  src/unit-tests/oscore-test/ut_oscore_task_test.c
Labels: CCB:Approved

#1085 Fix #1084, root task ID on RTEMS
  src/os/rtems/src/os-impl-tasks.c
Labels: CCB:Approved

#1090 Fix #1082, increase UT symbol dump size limit
  src/unit-tests/osloader-test/ut_osloader_symtable_test.c
Labels: CCB:Approved

#1091 Fix #1087, do not register RTOS timer for external sync
  src/os/vxworks/src/os-impl-timebase.c
  src/unit-test-coverage/vxworks/src/coveragetest-timebase.c
Labels: CCB:Approved, vxworks

#1093 Fix #1088, avoid task delete during UtPrintf
  src/bsp/generic-vxworks/src/bsp_start.c
  src/unit-tests/oscore-test/ut_oscore_task_test.c
Labels: CCB:Approved

#1097 Fix #1096, Add OSAL prefix to Network API group
  docs/src/osalmain.dox
  src/os/inc/osapi-network.h
  src/os/inc/osapi-sockets.h
Labels: CCB:Approved, docs

#1092 Fix #1086, increase timeout in network-api-test
  src/tests/network-api-test/network-api-test.c
Labels: CCB:Approved

#1089 Fix #1083, timer reconfig tests
  src/os/inc/osapi-timebase.h
  src/os/inc/osapi-timer.h
  src/os/posix/build_options.cmake
  src/os/rtems/build_options.cmake
  src/os/vxworks/build_options.cmake
  src/tests/time-base-api-test/time-base-api-test.c
  src/unit-tests/ostimer-test/ut_ostimer_test.c
Labels: CCB:Approved

#1106 Fix #1105, Add independent OS_rename functional test parameter checks
  src/unit-tests/osfile-test/ut_osfile_fileio_test.c
Labels: CCB:Ready

#1114 Fix #791, Add unit test branch coverage
  src/unit-test-coverage/portable/src/coveragetest-bsd-select.c
  src/unit-test-coverage/portable/src/coveragetest-posix-dirs.c
  src/unit-test-coverage/portable/src/coveragetest-posix-files.c
  src/unit-test-coverage/portable/src/coveragetest-posix-io.c
  src/unit-test-coverage/shared/src/coveragetest-binsem.c
  src/unit-test-coverage/shared/src/coveragetest-common.c
  src/unit-test-coverage/shared/src/coveragetest-countsem.c
  src/unit-test-coverage/shared/src/coveragetest-dir.c
  src/unit-test-coverage/shared/src/coveragetest-errors.c
  src/unit-test-coverage/shared/src/coveragetest-file.c
  src/unit-test-coverage/shared/src/coveragetest-filesys.c
  src/unit-test-coverage/shared/src/coveragetest-idmap.c
  src/unit-test-coverage/shared/src/coveragetest-module.c
  src/unit-test-coverage/shared/src/coveragetest-mutex.c
  src/unit-test-coverage/shared/src/coveragetest-network.c
  src/unit-test-coverage/shared/src/coveragetest-printf.c
  src/unit-test-coverage/shared/src/coveragetest-queue.c
  src/unit-test-coverage/shared/src/coveragetest-select.c
  src/unit-test-coverage/shared/src/coveragetest-sockets.c
  src/unit-test-coverage/shared/src/coveragetest-task.c
  src/unit-test-coverage/shared/src/coveragetest-time.c
  src/unit-test-coverage/shared/src/coveragetest-timebase.c
  src/unit-test-coverage/ut-stubs/src/osapi-shared-error-impl-table-stubs.c
  src/unit-test-coverage/vxworks/adaptors/inc/ut-adaptor-console.h
  src/unit-test-coverage/vxworks/adaptors/src/ut-adaptor-console.c
  src/unit-test-coverage/vxworks/src/coveragetest-common.c
  src/unit-test-coverage/vxworks/src/coveragetest-console.c
  src/unit-test-coverage/vxworks/src/coveragetest-filesys.c
  src/unit-test-coverage/vxworks/src/coveragetest-network.c
  src/unit-test-coverage/vxworks/src/coveragetest-shell.c
  src/unit-test-coverage/vxworks/src/coveragetest-symtab.c
  src/unit-test-coverage/vxworks/src/coveragetest-tasks.c
  src/unit-test-coverage/vxworks/src/coveragetest-timebase.c
Labels: CCB:Approved
