Repository nasa/osal, pull requests merged in 2021-03, with the labels that each got.

#834 Fix #833, Initialize file descriptor in OS_OpenCreate
  src/os/inc/osapi-file.h
  src/os/shared/src/osapi-file.c
  src/tests/file-api-test/file-api-test.c
Labels: CCB:FastTrack, IC:2021-03-02

#827 Fix #780, restrict permissions on file create
  ut_assert/src/uttools.c
Labels: CCB:2021-02-24, IC:2021-03-02

#829 Fix #828, fix comment style
  src/tests/select-test/select-test.c
Labels: CCB:2021-02-24, CCB:FastTrack, IC:2021-03-02, conflicts

#824 Fix #821, add accessor functions for version strings
  CMakeLists.txt
  src/os/inc/osapi-version.h
  src/os/shared/src/osapi-version.c
  src/unit-test-coverage/shared/CMakeLists.txt
  src/unit-test-coverage/shared/src/coveragetest-version.c
  src/ut-stubs/CMakeLists.txt
  src/ut-stubs/osapi-utstub-version.c
Labels: CCB:2021-02-24, IC:2021-03-02

#837 Fix #836, Add Testing Tools to the Security Policy
  SECURITY.md
Labels: CCB:FastTrack, docs

#890 Fix #875, Move copyblock size to define
  src/os/shared/src/osapi-file.c
Labels: CCB:FastTrack

#891 Fix #873, Remove rogue while loop in OS_DeleteAllObjects
  src/os/shared/src/osapi-common.c
Labels: CCB:FastTrack

#893 Fix #859, Consolidate duplicated switch in OS_SocketOpen_Impl
  src/os/portable/os-impl-bsd-sockets.c
Labels: CCB:FastTrack, IC:2021-03-23

#894 Fix #854, Const correct input pointers
  src/os/portable/os-impl-bsd-select.c
  src/os/shared/inc/os-shared-idmap.h
  src/os/shared/src/osapi-idmap.c
Labels: CCB:FastTrack, IC:2021-03-23

#895 Fix #851, Remove duplicate network prototypes
  src/os/inc/osapi-sockets.h
Labels: CCB:FastTrack, IC:2021-03-23

#896 Fix #842, Remove NULL redefine
  src/os/inc/common_types.h
Labels: CCB:FastTrack, IC:2021-03-23

#912 Fix #911, Add Contributing Guide
  CONTRIBUTING.md
Labels: CCB:FastTrack, docs

#914 Fix #752, Utilize UTASSERT_CASETYPE_NA to report OS_ERR_NOT_IMPLEMENTED
  src/tests/file-api-test/file-api-test.c
  src/tests/network-api-test/network-api-test.c
  src/tests/select-test/select-test.c
  src/tests/symbol-api-test/symbol-api-test.c
  ut_assert/inc/utassert.h
Labels: IC:2021-03-23

#897 Fix #855, check against FD_SETSIZE in bsd-select
  src/os/portable/os-impl-bsd-select.c
  src/unit-test-coverage/portable/adaptors/inc/ut-adaptor-portable-posix-io.h
  src/unit-test-coverage/portable/adaptors/src/ut-adaptor-portable-posix-io.c
  src/unit-test-coverage/portable/src/coveragetest-bsd-select.c
  src/unit-test-coverage/ut-stubs/inc/OCS_sys_select.h
  src/unit-test-coverage/ut-stubs/override_inc/sys/select.h
Labels: CCB:Ready, IC:2021-03-23, conflicts

#898 Fix #857, correct interval calculation in DoSelect
  src/os/portable/os-impl-bsd-select.c
  src/unit-test-coverage/portable/src/coveragetest-bsd-select.c
Labels: IC:2021-03-23

#909 Fix #862, comments describing select after connect
  src/os/portable/os-impl-bsd-sockets.c
Labels: IC:2021-03-23

#902 Fix #858, add check for EAGAIN in addition to EINTR
  src/os/portable/os-impl-bsd-select.c
Labels: IC:2021-03-23

#908 Fix #861, compile time assert for sockaddr size
  src/os/portable/os-impl-bsd-sockets.c
Labels: IC:2021-03-23

#840 Fix #416, add shell functional test
  src/tests/shell-test/shell-test.c
Labels: IC:2021-03-23, dependency

#903 Fix #867, better error translation for ESPIPE errno
  src/os/portable/os-impl-posix-io.c
  src/unit-test-coverage/portable/src/coveragetest-posix-io.c
Labels: IC:2021-03-23

#901 Fix #869, rename OS_U32ValueWrapper_t
  src/os/posix/src/os-impl-console.c
  src/os/posix/src/os-impl-tasks.c
  src/os/posix/src/os-impl-timebase.c
  src/os/rtems/src/os-impl-timebase.c
  src/os/shared/inc/os-shared-globaldefs.h
Labels: IC:2021-03-23

#900 Fix #876, break up logic in return statement
  src/os/shared/src/osapi-filesys.c
Labels: IC:2021-03-23

#907 Fix #889, report timer_gettime error
  src/os/vxworks/src/os-impl-timebase.c
  src/unit-test-coverage/vxworks/src/coveragetest-timebase.c
Labels: IC:2021-03-23

#906 Fix #886, return moduleInfoGet error
  src/os/vxworks/src/os-impl-loader.c
  src/unit-test-coverage/vxworks/src/coveragetest-loader.c
Labels: IC:2021-03-23

#905 Fix #882, make module comment same as other services
  src/os/shared/src/osapi-module.c
Labels: IC:2021-03-23

#899 Fix #883, remove unreachable test
  src/os/shared/src/osapi-mutex.c
Labels: IC:2021-03-23

#920 Fix #919, check index inside fdset conversions
  src/os/portable/os-impl-bsd-select.c
Labels: CCB:FastTrack, IC:2021-03-23

#922 Fix #921, make non-selectable FD an error
  src/os/portable/os-impl-bsd-select.c
  src/unit-test-coverage/portable/src/coveragetest-bsd-select.c
Labels: CCB:FastTrack, IC:2021-03-23

#878 Fix #843, remove BIG/LITTLE bit order macros
  src/os/inc/common_types.h
Labels: CCB:FastTrack, IC:2021-03-30

#918 Fix #846, Minor clean up and clarification in comments/naming
  src/os/inc/osapi-dir.h
  src/os/inc/osapi-select.h
  src/os/inc/osapi-task.h
  src/os/portable/os-impl-bsd-select.c
  src/os/portable/os-impl-posix-dirs.c
  src/os/shared/src/osapi-common.c
  src/os/shared/src/osapi-idmap.c
  src/os/shared/src/osapi-printf.c
  src/os/shared/src/osapi-queue.c
  src/os/shared/src/osapi-select.c
  src/os/vxworks/src/os-impl-console.c
  src/os/vxworks/src/os-impl-tasks.c
  src/os/vxworks/src/os-impl-timebase.c
Labels: CCB:FastTrack, IC:2021-03-30

#923 Fix #831, Finish os-impl-bsd-socket.c coverage testing
  src/unit-test-coverage/portable/src/coveragetest-bsd-sockets.c
  src/unit-test-coverage/ut-stubs/src/arpa-inet-stubs.c
  src/unit-test-coverage/ut-stubs/src/osapi-select-impl-stubs.c
  src/unit-test-coverage/ut-stubs/src/sys-socket-stubs.c
Labels: IC:2021-03-30

#915 Fix #888, better return codes from OS_SymbolTableDump_Impl
  src/os/inc/osapi-error.h
  src/os/vxworks/src/os-impl-symtab.c
  src/unit-test-coverage/vxworks/adaptors/inc/ut-adaptor-symtab.h
  src/unit-test-coverage/vxworks/adaptors/src/ut-adaptor-symtab.c
  src/unit-test-coverage/vxworks/src/coveragetest-symtab.c
Labels: IC:2021-03-30

#926 Fix #853, remove OS_TaskRegister
  src/examples/tasking-example/tasking-example.c
  src/os/inc/osapi-task.h
  src/os/shared/inc/os-shared-task.h
  src/os/shared/src/osapi-task.c
  src/tests/bin-sem-flush-test/bin-sem-flush-test.c
  src/tests/bin-sem-test/bin-sem-test.c
  src/tests/bin-sem-timeout-test/bin-sem-timeout-test.c
  src/tests/count-sem-test/count-sem-test.c
  src/tests/mutex-test/mutex-test.c
  src/tests/osal-core-test/osal-core-test.c
  src/tests/queue-test/queue-test.c
  src/tests/sem-speed-test/sem-speed-test.c
  src/unit-test-coverage/shared/src/coveragetest-task.c
  src/unit-tests/oscore-test/ut_oscore_task_test.c
  src/unit-tests/oscore-test/ut_oscore_test.c
  src/ut-stubs/osapi-utstub-task.c
Labels: IC:2021-03-30

#935 Fix #934, Remove unused SCRIPT_MODE flag
  src/tests/CMakeLists.txt
Labels: CCB:FastTrack, IC:2021-03-30

#930 Fix #929, use test function for osal_id_t
  src/tests/file-api-test/file-api-test.c
Labels: CCB:FastTrack, IC:2021-03-30
