Repository nasa/osal, pull requests merged in 2021-02, with the labels that each got.

#768 Fix #602, bring OSAL code coverage back up to 100%
  src/os/shared/inc/os-shared-file.h
  src/os/shared/inc/os-shared-filesys.h
  src/unit-test-coverage/portable/src/coveragetest-posix-dirs.c
  src/unit-test-coverage/shared/src/coveragetest-common.c
  src/unit-test-coverage/shared/src/coveragetest-file.c
  src/unit-test-coverage/shared/src/coveragetest-filesys.c
  src/unit-test-coverage/shared/src/coveragetest-module.c
  src/unit-test-coverage/shared/src/coveragetest-mutex.c
  src/unit-test-coverage/shared/src/coveragetest-queue.c
  src/unit-test-coverage/shared/src/coveragetest-time.c
  src/unit-test-coverage/vxworks/src/coveragetest-idmap.c
  src/unit-test-coverage/vxworks/src/coveragetest-tasks.c
  src/unit-test-coverage/vxworks/src/coveragetest-timebase.c
  src/ut-stubs/osapi-utstub-binsem.c
  src/ut-stubs/osapi-utstub-countsem.c
  src/ut-stubs/osapi-utstub-dir.c
  src/ut-stubs/osapi-utstub-file.c
  src/ut-stubs/osapi-utstub-filesys.c
  src/ut-stubs/osapi-utstub-idmap.c
  src/ut-stubs/osapi-utstub-module.c
  src/ut-stubs/osapi-utstub-mutex.c
  src/ut-stubs/osapi-utstub-queue.c
  src/ut-stubs/osapi-utstub-sockets.c
  src/ut-stubs/osapi-utstub-task.c
  src/ut-stubs/osapi-utstub-time.c
  src/ut-stubs/osapi-utstub-timebase.c
  src/ut-stubs/utstub-helpers.c
  src/ut-stubs/utstub-helpers.h
Labels: CCB:2021-01-27, IC:2021-02-02

#766 Fix #742, make sure all pointers are checked for null
  src/os/shared/src/osapi-binsem.c
  src/os/shared/src/osapi-clock.c
  src/os/shared/src/osapi-countsem.c
  src/os/shared/src/osapi-dir.c
  src/os/shared/src/osapi-errors.c
  src/os/shared/src/osapi-file.c
  src/os/shared/src/osapi-filesys.c
  src/os/shared/src/osapi-heap.c
  src/os/shared/src/osapi-idmap.c
  src/os/shared/src/osapi-module.c
  src/os/shared/src/osapi-printf.c
  src/os/shared/src/osapi-select.c
  src/os/shared/src/osapi-sockets.c
  src/os/shared/src/osapi-task.c
  src/os/shared/src/osapi-time.c
  src/os/shared/src/osapi-timebase.c
  src/unit-test-coverage/shared/src/coveragetest-idmap.c
Labels: CCB:2021-01-27, IC:2021-02-02

#772 Fix #771, Add workflow timeout and format check
  .github/workflows/format-check.yml
  .github/workflows/static-analysis.yml
  .travis.yml
  README.md
Labels: CCB:FastTrack, CCB:Ready, IC:2021-02-02, continuous-integration

#776 Fix #775, Add CodeQL analysis to workflow
  .github/workflows/codeql-build.yml
Labels: CCB:FastTrack, IC:2021-02-02, continuous-integration

#786 Fix #785, Clean commented out code
  src/tests/osal-core-test/osal-core-test.c
  src/unit-test-coverage/shared/src/coveragetest-idmap.c
  src/unit-tests/osfile-test/ut_osfile_fileio_test.c
Labels: CCB:FastTrack, IC:2021-02-02, unit-test

#784 Fix #783, Initialize locals flagged in static analysis
  src/os/shared/src/osapi-idmap.c
  src/unit-tests/osfile-test/ut_osfile_dirio_test.c
  src/ut-stubs/osapi-utstub-bsp.c
  src/ut-stubs/osapi-utstub-idmap.c
Labels: CCB:FastTrack, IC:2021-02-02

#789 Fix #788, Resolve coercion alters value warnings
  src/os/shared/src/osapi-errors.c
  src/os/shared/src/osapi-network.c
Labels: CCB:FastTrack, IC:2021-02-02, enhancement

#802 Fix #793, Remove unreachable code in OS_SocketOpen_Impl for BSD socket
  src/os/portable/os-impl-bsd-sockets.c
Labels: CCB:FastTrack, IC:2021-02-02

#782 Fix #781, Terminate UT macro variadic lists
  ut_assert/inc/utstubs.h
Labels: CCB:FastTrack, IC:2021-02-02

#804 Fix #803, Add check of semaphore to avoid unreachable code in posix OS_BinSemCreate_Impl
  src/os/posix/src/os-impl-binsem.c
Labels: CCB:FastTrack, IC:2021-02-02

#792 Fix #790, Return status from OS_ConsoleAPI_Init
  src/os/shared/src/osapi-printf.c
Labels: CCB:FastTrack, IC:2021-02-02

#778 Fix #777, Static allocation of DummyVec in OSC_INUM_TO_IVEC stub
  src/unit-test-coverage/ut-stubs/src/vxworks-intLib-stubs.c
Labels: CCB:FastTrack, IC:2021-02-02

#801 Fix #797, Update os-impl-no-symtab.c to match APIs
  src/os/portable/os-impl-no-symtab.c
Labels: CCB:FastTrack, IC:2021-02-02

#811 Fix #809, cast args to printf in queue-test
  src/tests/queue-test/queue-test.c
Labels: CCB:FastTrack, CCB:Ready, IC:2021-02-02

#810 Fix #808, length-limited string length checks
  src/os/shared/inc/os-shared-common.h
  src/os/shared/src/osapi-filesys.c
  src/os/shared/src/osapi-idmap.c
  src/os/shared/src/osapi-sockets.c
  src/os/vxworks/src/os-impl-shell.c
  src/os/vxworks/src/os-impl-symtab.c
  src/unit-test-coverage/shared/src/coveragetest-filesys.c
  src/unit-test-coverage/vxworks/src/coveragetest-symtab.c
Labels: CCB:FastTrack, CCB:Ready, IC:2021-02-02

#813 Fix #798 and #799, tests fail when no network
  src/tests/network-api-test/network-api-test.c
  src/tests/select-test/select-test.c
Labels: CCB:2021-02-17, IC:2021-02-23

#815 Fix #814, UT Stub match macro behavior
  src/ut-stubs/osapi-utstub-file.c
Labels: CCB:2021-02-17, IC:2021-02-23

#820 Fix #819, Remove redundant logic
  src/os/vxworks/src/os-impl-network.c
  src/os/vxworks/src/os-impl-timebase.c
Labels: CCB:2021-02-17, IC:2021-02-23

#818 Fix #817, Simplify name truncation in OS_CreateSocketName
  src/os/shared/src/osapi-sockets.c
Labels: CCB:2021-02-17, IC:2021-02-23

#794 Fix #779, Change global vars to not be hidden by local vars.
  src/tests/bin-sem-test/bin-sem-test.c
  src/tests/bin-sem-timeout-test/bin-sem-timeout-test.c
  src/tests/queue-test/queue-test.c
Labels: CCB:2021-02-17, IC:2021-02-23

#823 Fix #737, UT_Stub_CheckForceFail -> UT_Stub_CheckDefaultReturnValue
  ut_assert/inc/utstubs.h
  ut_assert/src/utstubs.c
Labels: CCB:2021-02-24, CCB:FastTrack, IC:2021-02-23, dependency

#822 Fix #770, Remove deprecated elements
  src/os/inc/osapi-file.h
  src/os/inc/osapi-filesys.h
  src/os/inc/osapi-os-core.h
  src/os/inc/osapi-os-filesys.h
  src/os/inc/osapi-os-loader.h
  src/os/inc/osapi-os-net.h
  src/os/inc/osapi-os-timer.h
  src/os/shared/src/osapi-file.c
  src/os/shared/src/osapi-filesys.c
  src/ut-stubs/osapi-utstub-file.c
  src/ut-stubs/osapi-utstub-filesys.c
  ut_assert/inc/utstubs.h
  ut_assert/src/utstubs.c
Labels: CCB:2021-02-24, CCB:FastTrack, IC:2021-02-23

#830 osal Integration candidate: 2021-02-23
  README.md
  src/os/inc/osapi-file.h
  src/os/inc/osapi-filesys.h
  src/os/inc/osapi-os-core.h
  src/os/inc/osapi-os-filesys.h
  src/os/inc/osapi-os-loader.h
  src/os/inc/osapi-os-net.h
  src/os/inc/osapi-os-timer.h
  src/os/inc/osapi-version.h
  src/os/shared/src/osapi-file.c
  src/os/shared/src/osapi-filesys.c
  src/os/shared/src/osapi-sockets.c
  src/os/vxworks/src/os-impl-network.c
  src/os/vxworks/src/os-impl-timebase.c
  src/tests/bin-sem-test/bin-sem-test.c
  src/tests/bin-sem-timeout-test/bin-sem-timeout-test.c
  src/tests/network-api-test/network-api-test.c
  src/tests/queue-test/queue-test.c
  src/tests/select-test/select-test.c
  src/ut-stubs/osapi-utstub-file.c
  src/ut-stubs/osapi-utstub-filesys.c
  ut_assert/inc/utstubs.h
  ut_assert/src/utstubs.c
Labels: IC:2021-02-23
