Repository nasa/osal, pull requests merged in 2021-06, with the labels that each got.

#1053 Fix #1023, resolve discrepancies between timer API and unit tests
  src/os/inc/osapi-timer.h
  src/os/shared/src/osapi-time.c
  src/tests/timer-add-api-test/timer-add-api-test.c
  src/unit-test-coverage/shared/src/coveragetest-time.c
  src/unit-tests/ostimer-test/ut_ostimer_test.c
  src/unit-tests/ostimer-test/ut_ostimer_test.h
  src/unit-tests/ostimer-test/ut_ostimer_timerio_test.c
  src/unit-tests/ostimer-test/ut_ostimer_timerio_test.h
Labels: CCB:Approved, IC:2021-06-01

#1040 Fix #1008, resolve discrepancies between binsem API and unit tests
  src/os/inc/osapi-binsem.h
Labels: CCB:Approved, IC:2021-06-01

#1029 Fix #1009, add missing clock retcode tests
  src/os/inc/osapi-clock.h
  src/unit-tests/oscore-test/ut_oscore_misc_test.c
Labels: CCB:Approved, IC:2021-06-01

#1046 Fix #1010, resolve discrepancies between common API and unit tests
  src/os/inc/osapi-common.h
  src/unit-tests/oscore-test/ut_oscore_misc_test.c
  src/unit-tests/oscore-test/ut_oscore_misc_test.h
  src/unit-tests/oscore-test/ut_oscore_test.c
Labels: CCB:Approved, IC:2021-06-01

#1041 Fix #1011, resolve discrepancies between countsem API and unit tests
  src/os/inc/osapi-countsem.h
Labels: CCB:Approved, IC:2021-06-01

#1045 Fix #1012, resolve discrepancies between dir API and unit tests
  src/os/inc/osapi-dir.h
  src/unit-tests/osfile-test/ut_osfile_dirio_test.c
Labels: CCB:Approved

#1043 Fix #1016, resolve discrepancies between module API and unit tests
  src/os/inc/osapi-module.h
  src/unit-tests/osloader-test/ut_osloader_module_test.c
  src/unit-tests/osloader-test/ut_osloader_symtable_test.c
Labels: CCB:Approved, IC:2021-06-01

#1044 Fix #1017, resolve discrepancies between mutex API and unit tests
  src/os/inc/osapi-mutex.h
Labels: CCB:Approved, IC:2021-06-01

#1038 Fix #1018, resolve discrepancies between queue API and unit tests
  src/os/inc/osapi-queue.h
  src/unit-tests/oscore-test/ut_oscore_queue_test.c
Labels: CCB:Approved, IC:2021-06-01

#1037 Fix #1021, resolve discrepancies between task API and unit tests
  src/os/inc/osapi-task.h
  src/unit-tests/oscore-test/ut_oscore_task_test.c
  src/unit-tests/oscore-test/ut_oscore_task_test.h
  src/unit-tests/oscore-test/ut_oscore_test.c
Labels: CCB:Approved, IC:2021-06-01

#1051 Fix #1022, resolve discrepancies between timebase API and unit tests
  src/os/inc/osapi-timebase.h
  src/tests/time-base-api-test/time-base-api-test.c
Labels: CCB:Approved, IC:2021-06-01

#1030 Fix #1024, check misc API return codes
  src/os/inc/osapi-heap.h
  src/os/inc/osapi-network.h
  src/os/inc/osapi-shell.h
  src/unit-tests/inc/ut_os_support.h
  src/unit-tests/oscore-test/ut_oscore_misc_test.c
  src/unit-tests/osfile-test/ut_osfile_fileio_test.c
Labels: CCB:Approved

#1039 Fix #1035, Rename CodeQL cFE Build and add Duplicate Job
  .github/workflows/codeql-cfe-build.yml
Labels: CCB:Approved, continuous-integration

#1049 Fix #1048, filter only whole words for keyword match
  src/ut-stubs/osapi-timebase-stubs.c
  ut_assert/scripts/generate_stubs.pl
Labels: CCB:Approved, IC:2021-06-01

#962 Fix #961, update OSAL Config Guide link
  README.md
Labels: CCB:Approved, CCB:FastTrack, IC:2021-06-01, community, docs

#1058 osal Integration candidate: 2021-06-01
  .github/workflows/codeql-cfe-build.yml
  CMakeLists.txt
  README.md
  doc/src/CMakeLists.txt
  doc/src/osal-apiguide.doxyfile.in
  doc/src/osal-common.doxyfile.in
  doc/src/osal_fs.dox
  doc/src/osal_timer.dox
  doc/src/osalmain.dox
  src/os/inc/osapi-binsem.h
  src/os/inc/osapi-clock.h
  src/os/inc/osapi-common.h
  src/os/inc/osapi-countsem.h
  src/os/inc/osapi-dir.h
  src/os/inc/osapi-heap.h
  src/os/inc/osapi-module.h
  src/os/inc/osapi-mutex.h
  src/os/inc/osapi-network.h
  src/os/inc/osapi-queue.h
  src/os/inc/osapi-shell.h
  src/os/inc/osapi-task.h
  src/os/inc/osapi-timebase.h
  src/os/inc/osapi-timer.h
  src/os/inc/osapi-version.h
  src/os/shared/src/osapi-idmap.c
  src/os/shared/src/osapi-time.c
  src/tests/time-base-api-test/time-base-api-test.c
  src/tests/timer-add-api-test/timer-add-api-test.c
  src/unit-test-coverage/shared/src/coveragetest-time.c
  src/unit-tests/inc/ut_os_support.h
  src/unit-tests/oscore-test/ut_oscore_misc_test.c
  src/unit-tests/oscore-test/ut_oscore_misc_test.h
  src/unit-tests/oscore-test/ut_oscore_queue_test.c
  src/unit-tests/oscore-test/ut_oscore_task_test.c
  src/unit-tests/oscore-test/ut_oscore_task_test.h
  src/unit-tests/oscore-test/ut_oscore_test.c
  src/unit-tests/osfile-test/ut_osfile_dirio_test.c
  src/unit-tests/osfile-test/ut_osfile_fileio_test.c
  src/unit-tests/osloader-test/ut_osloader_module_test.c
  src/unit-tests/osloader-test/ut_osloader_symtable_test.c
  src/unit-tests/ostimer-test/ut_ostimer_test.c
  src/unit-tests/ostimer-test/ut_ostimer_test.h
  src/unit-tests/ostimer-test/ut_ostimer_timerio_test.c
  src/unit-tests/ostimer-test/ut_ostimer_timerio_test.h
  src/ut-stubs/osapi-timebase-stubs.c
  ut_assert/scripts/generate_stubs.pl
Labels: IC:2021-06-01, community

#1042 Fix #1025, Implement Coding Standard Rules in CodeQL
  .github/workflows/codeql-cfe-build.yml
  .github/workflows/codeql-osal-default.yml
Labels: CCB:Approved, continuous-integration

#1071 Fix #1068, rename doc to docs
  .github/pull_request_template.md
  CMakeLists.txt
  README.md
  docs/GSC_18370_Corp_CLA_form_1219.pdf
  docs/GSC_18370_Ind_CLA_form_1219.pdf
  docs/OSAL-Configuration-Guide.md
  docs/src/CMakeLists.txt
  docs/src/osal-apiguide.doxyfile.in
  docs/src/osal-common.doxyfile.in
  docs/src/osal_fs.dox
  docs/src/osal_timer.dox
  docs/src/osalmain.dox
Labels: CCB:Approved, build-system, docs

#1065 Fix #1061, add mutex lock around UtAssert globals
  ut_assert/inc/utbsp.h
  ut_assert/src/utassert.c
  ut_assert/src/utbsp.c
  ut_assert/src/uttest.c
Labels: CCB:Approved

#1056 Fix #1013, resolve discrepancies between file API and unit tests
  src/os/inc/osapi-file.h
  src/unit-tests/osfile-test/ut_osfile_fileio_test.c
Labels: CCB:Approved, unit-test

#1057 Fix #1014, resolve discrepancies between filesys API and unit tests
  src/os/inc/osapi-filesys.h
  src/tests/file-sys-add-fixed-map-api-test/file-sys-add-fixed-map-api-test.c
  src/unit-tests/osfilesys-test/ut_osfilesys_diskio_test.c
Labels: CCB:Approved

#1055 Fix #1015, resolve discrepancies between idmap API and unit tests
  src/os/inc/osapi-idmap.h
  src/os/shared/src/osapi-idmap.c
  src/tests/idmap-api-test/idmap-api-test.c
  src/tests/osal-core-test/osal-core-test.c
  src/unit-test-coverage/shared/src/coveragetest-idmap.c
Labels: CCB:Approved

#1064 Fix #1019, resolve discrepancies between select API and unit tests
  src/os/inc/osapi-select.h
  src/tests/select-test/select-test.c
  src/unit-tests/oscore-test/ut_oscore_select_test.c
Labels: CCB:Approved

#1060 Fix #1020, resolve discrepancies between socket API and unit tests
  src/os/inc/osapi-sockets.h
  src/os/portable/os-impl-bsd-sockets.c
  src/tests/network-api-test/network-api-test.c
  src/unit-test-coverage/portable/src/coveragetest-bsd-sockets.c
Labels: CCB:Approved

#1063 Fix #1062, const correct OS_SelectFdIsSet
  src/os/inc/osapi-select.h
  src/os/shared/src/osapi-select.c
  src/ut-stubs/osapi-select-stubs.c
Labels: CCB:Approved

#1067 Fix #1036 Add Workflow to build and verify OSAL API Guide
  .github/workflows/build-osal-apiguide.yml
Labels: CCB:Approved

#1070 Fix #1069, add detail design template
  doc/osal-detaildesign.doxyfile.in
Labels: CCB:Approved

#1072 Fix #399, Update error codes and documentation
  src/os/inc/osapi-error.h
  src/os/shared/src/osapi-errors.c
Labels: CCB:Approved

#1075 Fix #1074, Increase UT object limit for testing
  src/ut-stubs/utstub-helpers.h
Labels: CCB:FastTrack, CCB:Ready

#1066 Fix #1052, implement missing parameter/retcode test permutations
  src/os/inc/osapi-filesys.h
  src/os/inc/osapi-network.h
  src/os/inc/osapi-task.h
  src/os/shared/src/osapi-filesys.c
  src/os/shared/src/osapi-queue.c
  src/tests/file-sys-add-fixed-map-api-test/file-sys-add-fixed-map-api-test.c
  src/tests/network-api-test/network-api-test.c
  src/tests/time-base-api-test/time-base-api-test.c
  src/tests/timer-add-api-test/timer-add-api-test.c
  src/unit-test-coverage/shared/src/coveragetest-binsem.c
  src/unit-test-coverage/shared/src/coveragetest-countsem.c
  src/unit-test-coverage/shared/src/coveragetest-dir.c
  src/unit-test-coverage/shared/src/coveragetest-filesys.c
  src/unit-test-coverage/shared/src/coveragetest-mutex.c
  src/unit-test-coverage/shared/src/coveragetest-queue.c
  src/unit-test-coverage/shared/src/coveragetest-task.c
  src/unit-tests/oscore-test/ut_oscore_binsem_test.c
  src/unit-tests/oscore-test/ut_oscore_countsem_test.c
  src/unit-tests/oscore-test/ut_oscore_mutex_test.c
  src/unit-tests/oscore-test/ut_oscore_queue_test.c
  src/unit-tests/oscore-test/ut_oscore_select_test.c
  src/unit-tests/oscore-test/ut_oscore_task_test.c
  src/unit-tests/osfile-test/ut_osfile_dirio_test.c
  src/unit-tests/osfile-test/ut_osfile_fileio_test.c
  src/unit-tests/osloader-test/ut_osloader_module_test.c
  src/unit-tests/osloader-test/ut_osloader_symtable_test.c
  src/unit-tests/osnetwork-test/ut_osnetwork_misc_test.c
  src/unit-tests/ostimer-test/ut_ostimer_timerio_test.c
Labels: CCB:Approved
