Repository nasa/osal, pull requests merged in 2022-03, with the labels that each got.

#1221 Fix #1220 Implement OS_ModuleGetInfo_Impl for RTEMS
  src/os/rtems/src/os-impl-loader.c
Labels: CCB:Approved, RTEMS

#1230 Partial #1225, Update cFS-build CodeQL reusable worfklow target
  .github/workflows/codeql-cfe-build.yml
Labels: CCB:Approved, continuous-integration

#1232 Fix #1231, Doxygen strip path and expose common config
  docs/osal-detaildesign.doxyfile.in
  docs/src/CMakeLists.txt
  docs/src/osal-apiguide.doxyfile.in
  docs/src/osal-common.doxyfile.in
Labels: CCB:Approved

#1238 Fix #1237, avoid calling memchr() with unknown size buffer
  ut_assert/inc/utassert.h
  ut_assert/src/utassert.c
Labels: CCB:Ready, unit-test
