Repository nasa/osal, pull requests merged in 2022-01, with the labels that each got.

#1190 Fix #1188, Reuse CodeQL, Static Analysis, Format Check
  .github/workflows/codeql-cfe-build.yml
  .github/workflows/codeql-osal-default.yml
  .github/workflows/format-check.yml
  .github/workflows/static-analysis.yml
Labels: continuous-integration

#1201 Fix #1200, Add missing space to UtAssert_STUB_COUNT
  ut_assert/inc/utassert.h
Labels: CCB:Approved

#1202 Fix #1196, Add UINT8 and UINT16 equivalents for UtAssert_UINT32_<Comparison> macros
  ut_assert/inc/utassert.h
Labels: CCB:Approved

#1203 Fix #1199, correct warnings on gcc11
  src/unit-test-coverage/portable/src/coveragetest-bsd-sockets.c
  src/unit-test-coverage/shared/src/coveragetest-clock.c
  src/unit-test-coverage/vxworks/src/coveragetest-tasks.c
  src/unit-tests/oscore-test/ut_oscore_task_test.c
Labels: CCB:Approved

#1206 Fix #1204, Search global and local symbol tables
  src/os/portable/os-impl-no-symtab.c
  src/os/portable/os-impl-posix-dl-symtab.c
  src/os/shared/inc/os-shared-module.h
  src/os/shared/src/osapi-module.c
  src/os/vxworks/src/os-impl-symtab.c
  src/unit-test-coverage/portable/src/coveragetest-no-symtab.c
  src/unit-test-coverage/shared/src/coveragetest-module.c
  src/unit-test-coverage/ut-stubs/src/os-shared-module-impl-stubs.c
  src/unit-test-coverage/vxworks/src/coveragetest-symtab.c
  src/unit-tests/osloader-test/ut_osloader_symtable_test.c
Labels: enhancement, CCB:Approved

#1211 Fix #1210, Set output in OS_stat handler
  src/ut-stubs/osapi-file-handlers.c
Labels: CCB:Approved

#1209 Fix #1208, typesafe definition of osal_id_t
  src/os/inc/common_types.h
  src/os/inc/osapi-idmap.h
Labels: CCB:Approved, dependency
