Repository nasa/osal, pull requests merged in 2024-01, with the labels that each got.

#1437 Fix #1420, updating OSAL to use new versioning system.
  src/os/inc/osapi-version.h
  src/os/shared/src/osapi-version.c
Labels: CCB:Approved

#1442 Fix #1441, patch build for old RTEMS
  src/os/rtems/inc/os-rtems.h
Labels: CCB:Approved

#1436 Fix pointer error in OS_GetErrorName
  src/os/shared/src/osapi-errors.c
Labels: CCB:Approved, Equuleus-rc2

#1368 Fix #1107, Remove unreachable branch (superfluous if condition)
  .github/workflows/standalone-build.yml
  src/os/shared/src/osapi-filesys.c
Labels: enhancement, CCB:Approved, coverage, Equuleus-rc2
