Repository nasa/osal, pull requests merged in 2024-02, with the labels that each got.

#1331 Fix #1330, Move variables declared mid-function to the top
  src/tests/time-base-api-test/time-base-api-test.c
  src/unit-test-coverage/shared/src/coveragetest-idmap.c
Labels: enhancement, CCB:Approved

#1357 Fix #1356, Remove stray remaining 'goto' in OSAL test code
  src/unit-tests/osfile-test/ut_osfile_test.c
Labels: CCB:Approved

#1448 Fix #1433, use virtual path as name for FS_BASED maps
  src/os/rtems/src/os-impl-filesys.c
  src/os/shared/src/osapi-filesys.c
  src/os/vxworks/src/os-impl-filesys.c
  src/tests/file-sys-add-fixed-map-api-test/file-sys-add-fixed-map-api-test.c
  src/unit-test-coverage/shared/src/coveragetest-filesys.c
  src/unit-test-coverage/vxworks/src/coveragetest-filesys.c
Labels: CCB:Approved

#1450 Fix #1449, POSIX implementation honors stack pointer
  src/examples/tasking-example/tasking-example.c
  src/os/posix/inc/os-impl-tasks.h
  src/os/posix/src/os-impl-console.c
  src/os/posix/src/os-impl-tasks.c
  src/os/posix/src/os-impl-timebase.c
  src/tests/bin-sem-test/bin-sem-test.c
  src/tests/bin-sem-timeout-test/bin-sem-timeout-test.c
  src/tests/count-sem-test/count-sem-test.c
  src/tests/osal-core-test/osal-core-test.c
  src/tests/osal-core-test/osal-core-test.h
  src/tests/queue-test/queue-test.c
Labels: bug, CCB:Approved
